// ============================================================
// IPL 2026 – Complete Static Data for SportyRadar
// ============================================================

export const iplTeams = [
  'Chennai Super Kings',
  'Delhi Capitals',
  'Gujarat Titans',
  'Kolkata Knight Riders',
  'Lucknow Super Giants',
  'Mumbai Indians',
  'Punjab Kings',
  'Rajasthan Royals',
  'Royal Challengers Bengaluru',
  'Sunrisers Hyderabad',
]

// ─────────────────────────────────────────────────────────────
// TEAM PLAYERS  (for TeamListPage – squad cards)
// ─────────────────────────────────────────────────────────────
export const iplTeamPlayers = {
  'Chennai Super Kings': [
    { name: 'Ruturaj Gaikwad', role: 'Batter', age: 28, batting: 'Right hand Bat', bowling: 'Right arm Offbreak', image: '' },
    { name: 'MS Dhoni', role: 'Wicketkeeper Batter', age: 44, batting: 'Right hand Bat', bowling: 'Right arm Medium', image: '' },
    { name: 'Sanju Samson', role: 'Wicketkeeper Batter', age: 31, batting: 'Right hand Bat', bowling: '—', image: '' },
    { name: 'Dewald Brevis', role: 'Middle order Batter', age: 22, batting: 'Right hand Bat', bowling: 'Legbreak', image: '' },
    { name: 'Sarfaraz Khan', role: 'Middle order Batter', age: 28, batting: 'Right hand Bat', bowling: 'Legbreak', image: '' },
    { name: 'Ayush Mhatre', role: 'Top order Batter', age: 18, batting: 'Right hand Bat', bowling: 'Right arm Offbreak', image: '' },
    { name: 'Kartik Sharma', role: 'Wicketkeeper Batter', age: 19, batting: 'Right hand Bat', bowling: '—', image: '' },
    { name: 'Urvil Patel', role: 'Wicketkeeper Batter', age: 27, batting: 'Right hand Bat', bowling: '—', image: '' },
    { name: 'Shivam Dube', role: 'Allrounder', age: 32, batting: 'Left hand Bat', bowling: 'Right arm Medium', image: '' },
    { name: 'Jamie Overton', role: 'Bowling Allrounder', age: 31, batting: 'Right hand Bat', bowling: 'Right arm Fast', image: '' },
    { name: 'Matthew Short', role: 'Batting Allrounder', age: 30, batting: 'Right hand Bat', bowling: 'Right arm Offbreak', image: '' },
    { name: 'Prashant Veer', role: 'Bowling Allrounder', age: 19, batting: 'Left hand Bat', bowling: 'Slow Left arm Orthodox', image: '' },
    { name: 'Anshul Kamboj', role: 'Bowling Allrounder', age: 24, batting: 'Right hand Bat', bowling: 'Right arm Medium', image: '' },
    { name: 'Aman Khan', role: 'Allrounder', age: 28, batting: 'Right hand Bat', bowling: 'Right arm Medium', image: '' },
    { name: 'Zak Foulkes', role: 'Allrounder', age: 23, batting: 'Right hand Bat', bowling: 'Right arm Medium', image: '' },
    { name: 'Ramakrishna Ghosh', role: 'Bowling Allrounder', age: 28, batting: 'Right hand Bat', bowling: 'Right arm Medium fast', image: '' },
    { name: 'Khaleel Ahmed', role: 'Bowler', age: 27, batting: 'Right hand Bat', bowling: 'Left arm Fast medium', image: '' },
    { name: 'Rahul Chahar', role: 'Bowler', age: 26, batting: 'Right hand Bat', bowling: 'Legbreak Googly', image: '' },
    { name: 'Nathan Ellis', role: 'Bowler', age: 31, batting: 'Right hand Bat', bowling: 'Right arm Fast medium', image: '' },
    { name: 'Noor Ahmad', role: 'Bowler', age: 20, batting: 'Right hand Bat', bowling: 'Left arm Wrist spin', image: '' },
    { name: 'Matt Henry', role: 'Bowler', age: 33, batting: 'Right hand Bat', bowling: 'Right arm Fast medium', image: '' },
    { name: 'Shreyas Gopal', role: 'Bowler', age: 32, batting: 'Right hand Bat', bowling: 'Legbreak', image: '' },
    { name: 'Gurjapneet Singh', role: 'Bowler', age: 27, batting: 'Right hand Bat', bowling: 'Left arm Medium fast', image: '' },
    { name: 'Akeal Hosein', role: 'Bowler', age: 32, batting: 'Left hand Bat', bowling: 'Slow Left arm Orthodox', image: '' },
    { name: 'Mukesh Choudhary', role: 'Bowler', age: 29, batting: 'Left hand Bat', bowling: 'Left arm Medium', image: '' },
  ],

  'Delhi Capitals': [
    { name: 'KL Rahul', role: 'Wicketkeeper Batter', age: 33, batting: 'Right hand Bat', bowling: '—', image: '' },
    { name: 'Jake Fraser-McGurk', role: 'Top order Batter', age: 22, batting: 'Right hand Bat', bowling: 'Right arm Offbreak', image: '' },
    { name: 'Harry Brook', role: 'Batter', age: 26, batting: 'Right hand Bat', bowling: 'Right arm Offbreak', image: '' },
    { name: 'Tristan Stubbs', role: 'Batter', age: 25, batting: 'Right hand Bat', bowling: 'Right arm Offbreak', image: '' },
    { name: 'Abishek Porel', role: 'Wicketkeeper Batter', age: 23, batting: 'Left hand Bat', bowling: '—', image: '' },
    { name: 'Nitish Rana', role: 'Middle order Batter', age: 31, batting: 'Left hand Bat', bowling: 'Right arm Medium', image: '' },
    { name: 'Prithvi Shaw', role: 'Opening Batter', age: 26, batting: 'Right hand Bat', bowling: 'Right arm Offbreak', image: '' },
    { name: 'Sameer Rizvi', role: 'Allrounder', age: 21, batting: 'Right hand Bat', bowling: 'Right arm Offbreak', image: '' },
    { name: 'Axar Patel', role: 'Allrounder', age: 31, batting: 'Left hand Bat', bowling: 'Slow Left arm Orthodox', image: '' },
    { name: 'Kuldeep Yadav', role: 'Bowler', age: 30, batting: 'Left hand Bat', bowling: 'Left arm Wrist spin', image: '' },
    { name: 'Mitchell Starc', role: 'Bowler', age: 35, batting: 'Left hand Bat', bowling: 'Left arm Fast', image: '' },
    { name: 'T Natarajan', role: 'Bowler', age: 34, batting: 'Left hand Bat', bowling: 'Left arm Medium', image: '' },
    { name: 'Mukesh Kumar', role: 'Bowler', age: 32, batting: 'Right hand Bat', bowling: 'Right arm Medium', image: '' },
    { name: 'Dushmantha Chameera', role: 'Bowler', age: 33, batting: 'Right hand Bat', bowling: 'Right arm Fast', image: '' },
    { name: 'Kyle Jamieson', role: 'Bowler', age: 30, batting: 'Right hand Bat', bowling: 'Right arm Fast medium', image: '' },
    { name: 'Ashutosh Sharma', role: 'Batting Allrounder', age: 27, batting: 'Right hand Bat', bowling: '—', image: '' },
    { name: 'Ajay Mandal', role: 'Allrounder', age: 29, batting: 'Left hand Bat', bowling: 'Slow Left arm Orthodox', image: '' },
    { name: 'Madhav Tiwari', role: 'Allrounder', age: 22, batting: 'Right hand Bat', bowling: 'Right arm Medium fast', image: '' },
    { name: 'Lungi Ngidi', role: 'Bowler', age: 29, batting: 'Right hand Bat', bowling: 'Right arm Fast medium', image: '' },
    { name: 'Vipraj Nigam', role: 'Bowler', age: 21, batting: 'Right hand Bat', bowling: 'Legbreak', image: '' },
    { name: 'Auqib Nabi', role: 'Bowler', age: 29, batting: 'Right hand Bat', bowling: 'Right arm Medium', image: '' },
    { name: 'Tripurana Vijay', role: 'Bowler', age: 24, batting: 'Right hand Bat', bowling: 'Right arm Offbreak', image: '' },
  ],

  'Gujarat Titans': [
    { name: 'Shubman Gill', role: 'Top order Batter', age: 26, batting: 'Right hand Bat', bowling: 'Right arm Offbreak', image: '' },
    { name: 'Jos Buttler', role: 'Wicketkeeper Batter', age: 35, batting: 'Right hand Bat', bowling: '—', image: '' },
    { name: 'Sai Sudharsan', role: 'Top order Batter', age: 24, batting: 'Left hand Bat', bowling: 'Legbreak', image: '' },
    { name: 'M Shahrukh Khan', role: 'Batter', age: 30, batting: 'Right hand Bat', bowling: 'Right arm Offbreak', image: '' },
    { name: 'Tom Banton', role: 'Wicketkeeper Batter', age: 27, batting: 'Right hand Bat', bowling: '—', image: '' },
    { name: 'Anuj Rawat', role: 'Wicketkeeper Batter', age: 26, batting: 'Left hand Bat', bowling: '—', image: '' },
    { name: 'Kumar Kushagra', role: 'Wicketkeeper Batter', age: 21, batting: 'Right hand Bat', bowling: '—', image: '' },
    { name: 'Glenn Phillips', role: 'Allrounder', age: 28, batting: 'Right hand Bat', bowling: 'Right arm Offbreak', image: '' },
    { name: 'Jason Holder', role: 'Bowling Allrounder', age: 34, batting: 'Right hand Bat', bowling: 'Right arm Medium fast', image: '' },
    { name: 'Rashid Khan', role: 'Bowling Allrounder', age: 27, batting: 'Right hand Bat', bowling: 'Legbreak Googly', image: '' },
    { name: 'Washington Sundar', role: 'Bowling Allrounder', age: 26, batting: 'Left hand Bat', bowling: 'Right arm Offbreak', image: '' },
    { name: 'Rahul Tewatia', role: 'Bowling Allrounder', age: 32, batting: 'Left hand Bat', bowling: 'Legbreak', image: '' },
    { name: 'Nishant Sindhu', role: 'Allrounder', age: 21, batting: 'Left hand Bat', bowling: 'Slow Left arm Orthodox', image: '' },
    { name: 'Manav Suthar', role: 'Bowling Allrounder', age: 23, batting: 'Left hand Bat', bowling: 'Slow Left arm Orthodox', image: '' },
    { name: 'Kagiso Rabada', role: 'Bowler', age: 30, batting: 'Left hand Bat', bowling: 'Right arm Fast', image: '' },
    { name: 'Mohammed Siraj', role: 'Bowler', age: 31, batting: 'Right hand Bat', bowling: 'Right arm Fast', image: '' },
    { name: 'Prasidh Krishna', role: 'Bowler', age: 29, batting: 'Right hand Bat', bowling: 'Right arm Fast medium', image: '' },
    { name: 'Sai Kishore', role: 'Bowler', age: 29, batting: 'Left hand Bat', bowling: 'Slow Left arm Orthodox', image: '' },
    { name: 'Ishant Sharma', role: 'Bowler', age: 37, batting: 'Right hand Bat', bowling: 'Right arm Fast medium', image: '' },
    { name: 'Gurnoor Brar', role: 'Bowler', age: 25, batting: 'Left hand Bat', bowling: 'Right arm Fast', image: '' },
    { name: 'Arshad Khan', role: 'Bowler', age: 27, batting: 'Left hand Bat', bowling: 'Left arm Fast medium', image: '' },
    { name: 'Ashok Sharma', role: 'Bowler', age: 23, batting: 'Right hand Bat', bowling: 'Right arm Medium', image: '' },
    { name: 'Luke Wood', role: 'Bowler', age: 30, batting: 'Left hand Bat', bowling: 'Left arm Fast medium', image: '' },
    { name: 'Jayant Yadav', role: 'Bowler', age: 35, batting: 'Right hand Bat', bowling: 'Right arm Offbreak', image: '' },
    { name: 'Prithvi Raj', role: 'Bowler', age: 27, batting: 'Left hand Bat', bowling: 'Left arm Medium', image: '' },
  ],

  'Kolkata Knight Riders': [
    { name: 'Ajinkya Rahane', role: 'Top order Batter', age: 37, batting: 'Right hand Bat', bowling: 'Right arm Medium', image: '' },
    { name: 'Rinku Singh', role: 'Middle order Batter', age: 28, batting: 'Left hand Bat', bowling: 'Right arm Offbreak', image: '' },
    { name: 'Rovman Powell', role: 'Middle order Batter', age: 32, batting: 'Right hand Bat', bowling: 'Right arm Medium fast', image: '' },
    { name: 'Angkrish Raghuvanshi', role: 'Top order Batter', age: 21, batting: 'Right hand Bat', bowling: 'Slow Left arm Orthodox', image: '' },
    { name: 'Finn Allen', role: 'Top order Batter', age: 26, batting: 'Right hand Bat', bowling: '—', image: '' },
    { name: 'Manish Pandey', role: 'Top order Batter', age: 36, batting: 'Right hand Bat', bowling: 'Right arm Medium', image: '' },
    { name: 'Ramandeep Singh', role: 'Middle order Batter', age: 28, batting: 'Right hand Bat', bowling: 'Right arm Medium', image: '' },
    { name: 'Sarthak Ranjan', role: 'Opening Batter', age: 29, batting: 'Right hand Bat', bowling: 'Legbreak', image: '' },
    { name: 'Rahul Tripathi', role: 'Top order Batter', age: 34, batting: 'Right hand Bat', bowling: 'Right arm Medium', image: '' },
    { name: 'Tejasvi Dahiya', role: 'Wicketkeeper Batter', age: 23, batting: 'Right hand Bat', bowling: '—', image: '' },
    { name: 'Tim Seifert', role: 'Wicketkeeper Batter', age: 30, batting: 'Right hand Bat', bowling: '—', image: '' },
    { name: 'Sunil Narine', role: 'Bowling Allrounder', age: 37, batting: 'Left hand Bat', bowling: 'Right arm Offbreak', image: '' },
    { name: 'Cameron Green', role: 'Batting Allrounder', age: 26, batting: 'Right hand Bat', bowling: 'Right arm Fast medium', image: '' },
    { name: 'Rachin Ravindra', role: 'Batting Allrounder', age: 25, batting: 'Left hand Bat', bowling: 'Slow Left arm Orthodox', image: '' },
    { name: 'Anukul Roy', role: 'Allrounder', age: 26, batting: 'Left hand Bat', bowling: 'Slow Left arm Orthodox', image: '' },
    { name: 'Daksh Kamra', role: 'Allrounder', age: 22, batting: 'Right hand Bat', bowling: 'Legbreak Googly', image: '' },
    { name: 'Varun Chakravarthy', role: 'Bowler', age: 34, batting: 'Right hand Bat', bowling: 'Legbreak Googly', image: '' },
    { name: 'Harshit Rana', role: 'Bowler', age: 23, batting: 'Right hand Bat', bowling: 'Right arm Fast', image: '' },
    { name: 'Akash Deep', role: 'Bowler', age: 28, batting: 'Right hand Bat', bowling: 'Right arm Fast medium', image: '' },
    { name: 'Vaibhav Arora', role: 'Bowler', age: 27, batting: 'Right hand Bat', bowling: 'Right arm Fast medium', image: '' },
    { name: 'Matheesha Pathirana', role: 'Bowler', age: 22, batting: 'Right hand Bat', bowling: 'Right arm Fast', image: '' },
    { name: 'Umran Malik', role: 'Bowler', age: 25, batting: 'Right hand Bat', bowling: 'Right arm Fast', image: '' },
    { name: 'Blessing Muzarabani', role: 'Bowler', age: 29, batting: 'Right hand Bat', bowling: 'Right arm Fast medium', image: '' },
    { name: 'Kartik Tyagi', role: 'Bowler', age: 25, batting: 'Right hand Bat', bowling: 'Right arm Fast', image: '' },
    { name: 'Prashant Solanki', role: 'Bowler', age: 25, batting: 'Right hand Bat', bowling: 'Legbreak', image: '' },
    { name: 'Mustafizur Rahman', role: 'Bowler', age: 30, batting: 'Left hand Bat', bowling: 'Left arm Fast medium', image: '' },
  ],

  'Lucknow Super Giants': [
    { name: 'Rishabh Pant', role: 'Wicketkeeper Batter', age: 28, batting: 'Left hand Bat', bowling: '—', image: '' },
    { name: 'Nicholas Pooran', role: 'Wicketkeeper Batter', age: 30, batting: 'Left hand Bat', bowling: '—', image: '' },
    { name: 'Aiden Markram', role: 'Batter', age: 31, batting: 'Right hand Bat', bowling: 'Right arm Offbreak', image: '' },
    { name: 'Abdul Samad', role: 'Batter', age: 24, batting: 'Right hand Bat', bowling: 'Legbreak', image: '' },
    { name: 'Ayush Badoni', role: 'Batter', age: 25, batting: 'Right hand Bat', bowling: 'Right arm Offbreak', image: '' },
    { name: 'Josh Inglis', role: 'Wicketkeeper Batter', age: 29, batting: 'Right hand Bat', bowling: '—', image: '' },
    { name: 'Himmat Singh', role: 'Batter', age: 30, batting: 'Right hand Bat', bowling: '—', image: '' },
    { name: 'Akshat Raghuwanshi', role: 'Middle order Batter', age: 22, batting: 'Right hand Bat', bowling: 'Right arm Offbreak', image: '' },
    { name: 'Matthew Breetzke', role: 'Batter', age: 27, batting: 'Right hand Bat', bowling: '—', image: '' },
    { name: 'Mukul Choudhary', role: 'Batter', age: 21, batting: 'Right hand Bat', bowling: '—', image: '' },
    { name: 'Mitchell Marsh', role: 'Allrounder', age: 33, batting: 'Left hand Bat', bowling: 'Right arm Fast medium', image: '' },
    { name: 'Wanindu Hasaranga', role: 'Allrounder', age: 27, batting: 'Right hand Bat', bowling: 'Legbreak Googly', image: '' },
    { name: 'Arshin Kulkarni', role: 'Allrounder', age: 19, batting: 'Left hand Bat', bowling: 'Slow Left arm Orthodox', image: '' },
    { name: 'Shahbaz Ahmed', role: 'Allrounder', age: 28, batting: 'Left hand Bat', bowling: 'Slow Left arm Orthodox', image: '' },
    { name: 'Mohammed Shami', role: 'Bowler', age: 35, batting: 'Right hand Bat', bowling: 'Right arm Fast medium', image: '' },
    { name: 'Mayank Yadav', role: 'Bowler', age: 23, batting: 'Right hand Bat', bowling: 'Right arm Fast', image: '' },
    { name: 'Avesh Khan', role: 'Bowler', age: 28, batting: 'Right hand Bat', bowling: 'Right arm Fast medium', image: '' },
    { name: 'Anrich Nortje', role: 'Bowler', age: 31, batting: 'Right hand Bat', bowling: 'Right arm Fast', image: '' },
    { name: 'Arjun Tendulkar', role: 'Bowler', age: 25, batting: 'Left hand Bat', bowling: 'Left arm Medium fast', image: '' },
    { name: 'Digvesh Rathi', role: 'Bowler', age: 20, batting: 'Right hand Bat', bowling: 'Legbreak Googly', image: '' },
    { name: 'Manimaran Siddharth', role: 'Bowler', age: 26, batting: 'Left hand Bat', bowling: 'Slow Left arm Orthodox', image: '' },
    { name: 'Mohsin Khan', role: 'Bowler', age: 27, batting: 'Left hand Bat', bowling: 'Left arm Fast medium', image: '' },
    { name: 'Akash Singh', role: 'Bowler', age: 22, batting: 'Right hand Bat', bowling: 'Left arm Medium', image: '' },
    { name: 'Naman Tiwari', role: 'Bowler', age: 21, batting: 'Left hand Bat', bowling: 'Left arm Fast medium', image: '' },
    { name: 'Prince Yadav', role: 'Bowler', age: 22, batting: 'Right hand Bat', bowling: 'Legbreak', image: '' },
  ],

  'Mumbai Indians': [
    { name: 'Rohit Sharma', role: 'Opening Batter', age: 38, batting: 'Right hand Bat', bowling: 'Right arm Offbreak', image: '' },
    { name: 'Suryakumar Yadav', role: 'Batter', age: 34, batting: 'Right hand Bat', bowling: 'Right arm Medium', image: '' },
    { name: 'Quinton de Kock', role: 'Wicketkeeper Batter', age: 32, batting: 'Left hand Bat', bowling: '—', image: '' },
    { name: 'Ryan Rickelton', role: 'Batter', age: 27, batting: 'Left hand Bat', bowling: '—', image: '' },
    { name: 'Sherfane Rutherford', role: 'Batter', age: 27, batting: 'Left hand Bat', bowling: 'Right arm Medium', image: '' },
    { name: 'Danish Malewar', role: 'Batter', age: 23, batting: 'Right hand Bat', bowling: '—', image: '' },
    { name: 'Robin Minz', role: 'Wicketkeeper Batter', age: 22, batting: 'Right hand Bat', bowling: '—', image: '' },
    { name: 'Hardik Pandya', role: 'Allrounder', age: 31, batting: 'Right hand Bat', bowling: 'Right arm Fast medium', image: '' },
    { name: 'Tilak Varma', role: 'Allrounder', age: 22, batting: 'Left hand Bat', bowling: 'Right arm Offbreak', image: '' },
    { name: 'Will Jacks', role: 'Allrounder', age: 26, batting: 'Right hand Bat', bowling: 'Right arm Offbreak', image: '' },
    { name: 'Mitchell Santner', role: 'Allrounder', age: 33, batting: 'Left hand Bat', bowling: 'Slow Left arm Orthodox', image: '' },
    { name: 'Shardul Thakur', role: 'Allrounder', age: 33, batting: 'Right hand Bat', bowling: 'Right arm Fast medium', image: '' },
    { name: 'Naman Dhir', role: 'Allrounder', age: 23, batting: 'Right hand Bat', bowling: 'Right arm Offbreak', image: '' },
    { name: 'Raj Bawa', role: 'Allrounder', age: 23, batting: 'Right hand Bat', bowling: 'Right arm Fast medium', image: '' },
    { name: 'Corbin Bosch', role: 'Allrounder', age: 28, batting: 'Right hand Bat', bowling: 'Right arm Fast medium', image: '' },
    { name: 'Atharva Ankolekar', role: 'Allrounder', age: 28, batting: 'Left hand Bat', bowling: 'Slow Left arm Orthodox', image: '' },
    { name: 'Mayank Rawat', role: 'Allrounder', age: 23, batting: 'Left hand Bat', bowling: '—', image: '' },
    { name: 'Jasprit Bumrah', role: 'Bowler', age: 31, batting: 'Right hand Bat', bowling: 'Right arm Fast medium', image: '' },
    { name: 'Trent Boult', role: 'Bowler', age: 36, batting: 'Left hand Bat', bowling: 'Left arm Fast medium', image: '' },
    { name: 'Deepak Chahar', role: 'Bowler', age: 32, batting: 'Right hand Bat', bowling: 'Right arm Fast medium', image: '' },
    { name: 'AM Ghazanfar', role: 'Bowler', age: 19, batting: 'Right hand Bat', bowling: 'Right arm Offbreak', image: '' },
    { name: 'Ashwani Kumar', role: 'Bowler', age: 27, batting: 'Left hand Bat', bowling: 'Left arm Fast medium', image: '' },
    { name: 'Mayank Markande', role: 'Bowler', age: 28, batting: 'Right hand Bat', bowling: 'Legbreak Googly', image: '' },
    { name: 'Mohd Izhar', role: 'Bowler', age: 21, batting: 'Right hand Bat', bowling: 'Right arm Medium', image: '' },
    { name: 'Raghu Sharma', role: 'Bowler', age: 25, batting: 'Right hand Bat', bowling: 'Legbreak', image: '' },
  ],

  'Punjab Kings': [
    { name: 'Shreyas Iyer', role: 'Batter', age: 30, batting: 'Right hand Bat', bowling: 'Right arm Offbreak', image: '' },
    { name: 'Priyansh Arya', role: 'Opening Batter', age: 23, batting: 'Left hand Bat', bowling: '—', image: '' },
    { name: 'Prabhsimran Singh', role: 'Wicketkeeper Batter', age: 24, batting: 'Right hand Bat', bowling: '—', image: '' },
    { name: 'Nehal Wadhera', role: 'Batter', age: 24, batting: 'Left hand Bat', bowling: '—', image: '' },
    { name: 'Harnoor Singh', role: 'Batter', age: 21, batting: 'Left hand Bat', bowling: '—', image: '' },
    { name: 'Pyla Avinash', role: 'Batter', age: 24, batting: 'Right hand Bat', bowling: 'Right arm Offbreak', image: '' },
    { name: 'Vishnu Vinod', role: 'Wicketkeeper Batter', age: 30, batting: 'Right hand Bat', bowling: '—', image: '' },
    { name: 'Shashank Singh', role: 'Allrounder', age: 33, batting: 'Right hand Bat', bowling: 'Right arm Medium', image: '' },
    { name: 'Marcus Stoinis', role: 'Allrounder', age: 35, batting: 'Right hand Bat', bowling: 'Right arm Fast medium', image: '' },
    { name: 'Marco Jansen', role: 'Allrounder', age: 25, batting: 'Left hand Bat', bowling: 'Left arm Fast medium', image: '' },
    { name: 'Azmatullah Omarzai', role: 'Allrounder', age: 25, batting: 'Right hand Bat', bowling: 'Right arm Medium fast', image: '' },
    { name: 'Cooper Connolly', role: 'Allrounder', age: 22, batting: 'Left hand Bat', bowling: 'Right arm Offbreak', image: '' },
    { name: 'Musheer Khan', role: 'Allrounder', age: 20, batting: 'Left hand Bat', bowling: 'Slow Left arm Orthodox', image: '' },
    { name: 'Mitchell Owen', role: 'Allrounder', age: 23, batting: 'Left hand Bat', bowling: 'Right arm Medium', image: '' },
    { name: 'Suryansh Shedge', role: 'Allrounder', age: 21, batting: 'Right hand Bat', bowling: 'Right arm Offbreak', image: '' },
    { name: 'Arshdeep Singh', role: 'Bowler', age: 25, batting: 'Left hand Bat', bowling: 'Left arm Fast medium', image: '' },
    { name: 'Yuzvendra Chahal', role: 'Bowler', age: 35, batting: 'Right hand Bat', bowling: 'Legbreak Googly', image: '' },
    { name: 'Lockie Ferguson', role: 'Bowler', age: 33, batting: 'Right hand Bat', bowling: 'Right arm Fast', image: '' },
    { name: 'Xavier Bartlett', role: 'Bowler', age: 25, batting: 'Right hand Bat', bowling: 'Right arm Fast medium', image: '' },
    { name: 'Harpreet Brar', role: 'Bowler', age: 28, batting: 'Left hand Bat', bowling: 'Slow Left arm Orthodox', image: '' },
    { name: 'Vijaykumar Vyshak', role: 'Bowler', age: 28, batting: 'Right hand Bat', bowling: 'Right arm Fast medium', image: '' },
    { name: 'Yash Thakur', role: 'Bowler', age: 25, batting: 'Right hand Bat', bowling: 'Right arm Fast medium', image: '' },
    { name: 'Praveen Dubey', role: 'Bowler', age: 29, batting: 'Right hand Bat', bowling: 'Right arm Offbreak', image: '' },
    { name: 'Ben Dwarshuis', role: 'Bowler', age: 30, batting: 'Left hand Bat', bowling: 'Left arm Fast medium', image: '' },
    { name: 'Vishal Nishad', role: 'Bowler', age: 22, batting: 'Right hand Bat', bowling: 'Right arm Fast medium', image: '' },
  ],

  'Rajasthan Royals': [
    { name: 'Yashasvi Jaiswal', role: 'Opening Batter', age: 23, batting: 'Left hand Bat', bowling: 'Slow Left arm Orthodox', image: '' },
    { name: 'Riyan Parag', role: 'Batter', age: 23, batting: 'Right hand Bat', bowling: 'Right arm Offbreak', image: '' },
    { name: 'Shimron Hetmyer', role: 'Batter', age: 27, batting: 'Left hand Bat', bowling: '—', image: '' },
    { name: 'Dhruv Jurel', role: 'Wicketkeeper Batter', age: 24, batting: 'Right hand Bat', bowling: '—', image: '' },
    { name: 'Vaibhav Sooryavanshi', role: 'Opening Batter', age: 14, batting: 'Right hand Bat', bowling: 'Right arm Offbreak', image: '' },
    { name: 'Aman Rao', role: 'Batter', age: 25, batting: 'Left hand Bat', bowling: '—', image: '' },
    { name: 'Shubham Dubey', role: 'Batter', age: 24, batting: 'Right hand Bat', bowling: 'Right arm Offbreak', image: '' },
    { name: 'Lhuan-dre Pretorius', role: 'Batter', age: 24, batting: 'Right hand Bat', bowling: 'Right arm Fast medium', image: '' },
    { name: 'Ravi Singh', role: 'Batter', age: 21, batting: 'Right hand Bat', bowling: '—', image: '' },
    { name: 'Ravindra Jadeja', role: 'Allrounder', age: 36, batting: 'Left hand Bat', bowling: 'Slow Left arm Orthodox', image: '' },
    { name: 'Sam Curran', role: 'Allrounder', age: 26, batting: 'Left hand Bat', bowling: 'Left arm Fast medium', image: '' },
    { name: 'Donovan Ferreira', role: 'Allrounder', age: 28, batting: 'Right hand Bat', bowling: 'Right arm Offbreak', image: '' },
    { name: 'Jofra Archer', role: 'Bowler', age: 30, batting: 'Right hand Bat', bowling: 'Right arm Fast', image: '' },
    { name: 'Ravi Bishnoi', role: 'Bowler', age: 24, batting: 'Right hand Bat', bowling: 'Legbreak Googly', image: '' },
    { name: 'Tushar Deshpande', role: 'Bowler', age: 29, batting: 'Right hand Bat', bowling: 'Right arm Fast medium', image: '' },
    { name: 'Sandeep Sharma', role: 'Bowler', age: 31, batting: 'Right hand Bat', bowling: 'Right arm Medium', image: '' },
    { name: 'Nandre Burger', role: 'Bowler', age: 27, batting: 'Left hand Bat', bowling: 'Left arm Fast medium', image: '' },
    { name: 'Adam Milne', role: 'Bowler', age: 33, batting: 'Right hand Bat', bowling: 'Right arm Fast', image: '' },
    { name: 'Kwena Maphaka', role: 'Bowler', age: 19, batting: 'Right hand Bat', bowling: 'Left arm Fast', image: '' },
    { name: 'Sushant Mishra', role: 'Bowler', age: 24, batting: 'Right hand Bat', bowling: 'Right arm Fast medium', image: '' },
    { name: 'Yudhvir Singh', role: 'Bowler', age: 24, batting: 'Right hand Bat', bowling: 'Right arm Offbreak', image: '' },
    { name: 'Kuldeep Sen', role: 'Bowler', age: 28, batting: 'Right hand Bat', bowling: 'Right arm Fast medium', image: '' },
    { name: 'Brijesh Sharma', role: 'Bowler', age: 20, batting: 'Right hand Bat', bowling: 'Right arm Fast medium', image: '' },
    { name: 'Vignesh Puthur', role: 'Bowler', age: 22, batting: 'Right hand Bat', bowling: 'Left arm Fast medium', image: '' },
    { name: 'Yash Raj Punja', role: 'Bowler', age: 20, batting: 'Left hand Bat', bowling: 'Left arm Fast medium', image: '' },
  ],

  'Royal Challengers Bengaluru': [
    { name: 'Virat Kohli', role: 'Batter', age: 37, batting: 'Right hand Bat', bowling: 'Right arm Medium', image: 'https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcSHkz-CtfvMGgRgdHNQsxEMfsV37rycmXyYn4jbyBlVnEZZ-edxrgDlTl1Rbfo6teEkc2zsRuzlDUSc71RWUp5JtoegBcvnZPuUMwRmkDw&s=10' },
    { name: 'Rajat Patidar', role: 'Batter', age: 31, batting: 'Right hand Bat', bowling: 'Right arm Offbreak', image: '' },
    { name: 'Phil Salt', role: 'Wicketkeeper Batter', age: 28, batting: 'Right hand Bat', bowling: 'Right arm Offbreak', image: '' },
    { name: 'Tim David', role: 'Batter', age: 29, batting: 'Right hand Bat', bowling: '—', image: '' },
    { name: 'Devdutt Padikkal', role: 'Opening Batter', age: 25, batting: 'Left hand Bat', bowling: 'Right arm Offbreak', image: '' },
    { name: 'Jordan Cox', role: 'Batter', age: 25, batting: 'Right hand Bat', bowling: 'Right arm Offbreak', image: '' },
    { name: 'Jitesh Sharma', role: 'Wicketkeeper Batter', age: 31, batting: 'Right hand Bat', bowling: '—', image: '' },
    { name: 'Venkatesh Iyer', role: 'Allrounder', age: 30, batting: 'Left hand Bat', bowling: 'Right arm Medium', image: '' },
    { name: 'Krunal Pandya', role: 'Allrounder', age: 34, batting: 'Left hand Bat', bowling: 'Slow Left arm Orthodox', image: '' },
    { name: 'Jacob Bethell', role: 'Allrounder', age: 22, batting: 'Left hand Bat', bowling: 'Slow Left arm Orthodox', image: '' },
    { name: 'Romario Shepherd', role: 'Allrounder', age: 31, batting: 'Right hand Bat', bowling: 'Right arm Fast medium', image: '' },
    { name: 'Kanishk Chouhan', role: 'Allrounder', age: 21, batting: 'Right hand Bat', bowling: 'Right arm Offbreak', image: '' },
    { name: 'Vihaan Malhotra', role: 'Allrounder', age: 20, batting: 'Right hand Bat', bowling: 'Right arm Offbreak', image: '' },
    { name: 'Mangesh Yadav', role: 'Allrounder', age: 22, batting: 'Right hand Bat', bowling: 'Right arm Medium fast', image: '' },
    { name: 'Josh Hazlewood', role: 'Bowler', age: 34, batting: 'Right hand Bat', bowling: 'Right arm Fast medium', image: '' },
    { name: 'Bhuvneshwar Kumar', role: 'Bowler', age: 35, batting: 'Right hand Bat', bowling: 'Right arm Fast medium', image: '' },
    { name: 'Yash Dayal', role: 'Bowler', age: 27, batting: 'Left hand Bat', bowling: 'Left arm Fast medium', image: '' },
    { name: 'Nuwan Thushara', role: 'Bowler', age: 29, batting: 'Right hand Bat', bowling: 'Right arm Fast medium', image: '' },
    { name: 'Suyash Sharma', role: 'Bowler', age: 22, batting: 'Right hand Bat', bowling: 'Legbreak', image: '' },
    { name: 'Vicky Ostwal', role: 'Bowler', age: 23, batting: 'Right hand Bat', bowling: 'Slow Left arm Orthodox', image: '' },
    { name: 'Rasikh Salam', role: 'Bowler', age: 23, batting: 'Right hand Bat', bowling: 'Right arm Fast medium', image: '' },
    { name: 'Jacob Duffy', role: 'Bowler', age: 30, batting: 'Left hand Bat', bowling: 'Right arm Fast medium', image: '' },
    { name: 'Swapnil Singh', role: 'Bowler', age: 35, batting: 'Right hand Bat', bowling: 'Slow Left arm Orthodox', image: '' },
    { name: 'Abhinandan Singh', role: 'Bowler', age: 22, batting: 'Right hand Bat', bowling: 'Right arm Fast medium', image: '' },
    { name: 'Satvik Deswal', role: 'Bowler', age: 20, batting: 'Right hand Bat', bowling: 'Left arm Fast medium', image: '' },
  ],

  'Sunrisers Hyderabad': [
    { name: 'Travis Head', role: 'Opening Batter', age: 31, batting: 'Left hand Bat', bowling: 'Right arm Offbreak', image: '' },
    { name: 'Heinrich Klaasen', role: 'Wicketkeeper Batter', age: 33, batting: 'Right hand Bat', bowling: '—', image: '' },
    { name: 'Ishan Kishan', role: 'Wicketkeeper Batter', age: 27, batting: 'Left hand Bat', bowling: '—', image: '' },
    { name: 'Abhishek Sharma', role: 'Allrounder', age: 24, batting: 'Left hand Bat', bowling: 'Slow Left arm Orthodox', image: '' },
    { name: 'Nitish Kumar Reddy', role: 'Allrounder', age: 22, batting: 'Right hand Bat', bowling: 'Right arm Fast medium', image: '' },
    { name: 'Salil Arora', role: 'Batter', age: 30, batting: 'Right hand Bat', bowling: '—', image: '' },
    { name: 'Ravichandran Smaran', role: 'Batter', age: 26, batting: 'Right hand Bat', bowling: 'Right arm Offbreak', image: '' },
    { name: 'Aniket Verma', role: 'Batter', age: 22, batting: 'Right hand Bat', bowling: '—', image: '' },
    { name: 'Liam Livingstone', role: 'Allrounder', age: 32, batting: 'Right hand Bat', bowling: 'Legbreak', image: '' },
    { name: 'Harshal Patel', role: 'Allrounder', age: 34, batting: 'Right hand Bat', bowling: 'Right arm Fast medium', image: '' },
    { name: 'Kamindu Mendis', role: 'Allrounder', age: 26, batting: 'Left hand Bat', bowling: 'Slow Left arm Orthodox', image: '' },
    { name: 'Brydon Carse', role: 'Allrounder', age: 29, batting: 'Right hand Bat', bowling: 'Right arm Fast medium', image: '' },
    { name: 'Shivam Mavi', role: 'Allrounder', age: 27, batting: 'Right hand Bat', bowling: 'Right arm Fast medium', image: '' },
    { name: 'Harsh Dubey', role: 'Allrounder', age: 28, batting: 'Right hand Bat', bowling: 'Right arm Offbreak', image: '' },
    { name: 'Jack Edwards', role: 'Allrounder', age: 25, batting: 'Right hand Bat', bowling: 'Right arm Fast medium', image: '' },
    { name: 'Krains Fuletra', role: 'Allrounder', age: 22, batting: 'Right hand Bat', bowling: 'Right arm Offbreak', image: '' },
    { name: 'Shivang Kumar', role: 'Allrounder', age: 22, batting: 'Right hand Bat', bowling: 'Left arm Fast medium', image: '' },
    { name: 'Pat Cummins', role: 'Bowler', age: 32, batting: 'Right hand Bat', bowling: 'Right arm Fast medium', image: '' },
    { name: 'Jaydev Unadkat', role: 'Bowler', age: 33, batting: 'Left hand Bat', bowling: 'Left arm Fast medium', image: '' },
    { name: 'Zeeshan Ansari', role: 'Bowler', age: 25, batting: 'Left hand Bat', bowling: 'Slow Left arm Orthodox', image: '' },
    { name: 'Amit Kumar', role: 'Bowler', age: 22, batting: 'Right hand Bat', bowling: 'Right arm Fast medium', image: '' },
    { name: 'Praful Hinge', role: 'Bowler', age: 27, batting: 'Right hand Bat', bowling: 'Right arm Medium', image: '' },
    { name: 'Eshan Malinga', role: 'Bowler', age: 20, batting: 'Right hand Bat', bowling: 'Right arm Fast medium', image: '' },
    { name: 'Sakib Hussain', role: 'Bowler', age: 23, batting: 'Right hand Bat', bowling: 'Right arm Fast medium', image: '' },
    { name: 'Onkar Tarmale', role: 'Bowler', age: 22, batting: 'Right hand Bat', bowling: 'Right arm Medium', image: '' },
  ],
}

// ─────────────────────────────────────────────────────────────
// PLAYER DETAIL  (for PlayerDetailPage)
// ─────────────────────────────────────────────────────────────
export const playerDetail = [
  // ── CHENNAI SUPER KINGS ──────────────────────────────────
  {
    name: 'Ruturaj Gaikwad',
    image: '',
    born: 'January 31, 1997 (28 years)',
    birthPlace: 'Pune, Maharashtra',
    height: 'N/A',
    role: 'Batter',
    battingStyle: 'Right Handed Bat',
    bowlingStyle: 'Right arm Offbreak',
    team: 'Chennai Super Kings',
    summary: `Now in his third year as captain, the boy from Mumbai, Ruturaj Gaikwad has matured into the "Prince of Chennai." After leading India in recent T20I assignments, his role in 2026 is twofold: providing elite stability at the top of the order and managing a squad featuring high-priced uncapped stars.\n\nGaikwad's ability to anchor the innings allows CSK's explosive middle-order to flourish and go hammer and tongs at will. No matter what team he plays with, he is always expected to be the leading run-getter and he will be CSK's primary contender for the Orange Cap. He is known to utilise his refined technique against both pace and spin at the Chepauk and guide his team to victory every time they take the field.`,
  },
  {
    name: 'MS Dhoni',
    image: '',
    born: 'July 07, 1981 (44 years)',
    birthPlace: 'Ranchi, Jharkhand',
    height: '5 ft 9 in (175 cm)',
    role: 'Wicketkeeper Batter',
    battingStyle: 'Right Handed Bat',
    bowlingStyle: 'Right arm Medium',
    team: 'Chennai Super Kings',
    summary: `He is the undisputed king of CSK. Retained as an "uncapped player" under the revised regulations, M.S. Dhoni's presence remains the spiritual heartbeat of the team. In 2026, he is expected to play a specialised role as a lower-order finisher and tactical mentor to Gaikwad.\n\nWhile his glovework remains world-class, his ability to manipulate fields and guide young bowlers like Prashant Veer will be his greatest contribution. For fans, every ball he faces in what is widely rumored to be his final season is an event in itself.`,
  },
  {
    name: 'Sanju Samson',
    image: '',
    born: 'November 11, 1994 (31 years)',
    birthPlace: 'Pathanamthitta, Kerala',
    height: '5 ft 9 in',
    role: 'Wicketkeeper Batter',
    battingStyle: 'Right Handed Bat',
    bowlingStyle: '—',
    team: 'Chennai Super Kings',
    summary: `The blockbuster trade of 2026, Sanju Samson arrives from RR to bolster the top order. A hero of India's recent T20 World Cup win, Samson brings fearless aggression and a high strike rate against spin to Chennai's batting unit—a perfect fit for the Chepauk track.\n\nWhether he opens with Gaikwad or slots in at No. 3, his role is to ensure CSK doesn't stagnate in the powerplay. His leadership experience also adds another layer of strategic depth to the leadership group.`,
  },
  {
    name: 'Sarfaraz Khan',
    image: '',
    born: 'October 27, 1997 (28 years)',
    birthPlace: 'Mumbai, Maharashtra',
    height: 'N/A',
    role: 'Middle order Batter',
    battingStyle: 'Right Handed Bat',
    bowlingStyle: 'Legbreak',
    team: 'Chennai Super Kings',
    summary: `The run machine in the domestic circuit, Sarfaraz Khan is a batting prodigy who has already made a mark in the Indian national team. Acquired in the 2026 mini-auction, Sarfaraz provides a unique solution to middle-order spin problems. Known for his unconventional sweeps and ramps, he is statistically one of the best players of domestic spin in India.\n\nIn the context of IPL 2026, Sarfaraz acts as the bridge between the openers and the finishers, capable of keeping the scoreboard ticking during the middle overs and switching gears at will when needed.`,
  },
  {
    name: 'Dewald Brevis',
    image: '',
    born: 'June 06, 2003 (22 years)',
    birthPlace: 'Pretoria, South Africa',
    height: 'N/A',
    role: 'Middle order Batter',
    battingStyle: 'Right Handed Bat',
    bowlingStyle: 'Legbreak',
    team: 'Chennai Super Kings',
    summary: `Fondly known as "Baby AB," Dewald Brevis, the prodigal talent from the rainbow nation, remains a key overseas retention for CSK. In 2026, Brevis is expected to fully realise his potential as a 360-degree aggressor. His ability to take down world-class pace makes him a vital asset for away games on flatter decks.\n\nWith a few seasons of IPL experience now under his belt, the focus for Brevis this year is consistency, aiming to turn his explosive cameos into match-winning knocks.`,
  },
  {
    name: 'Ayush Mhatre',
    image: '',
    born: 'December 21, 2006 (18 years)',
    birthPlace: 'Mumbai, Maharashtra',
    height: 'N/A',
    role: 'Top order Batter',
    battingStyle: 'Right Handed Bat',
    bowlingStyle: 'Right arm Offbreak',
    team: 'Chennai Super Kings',
    summary: `A bright young talent retained by the franchise, Mhatre represents the "future" of CSK. Playing under the watchful eyes of seniors like Samson, Ruturaj and Dhoni, he is sure to bloom into a superstar.\n\nAs a technically sound right-hander who impressed in the domestic circuit, he provides excellent backup for the opening slots. In 2026, expect him to be used as a tactical "Impact Player" if the team needs to bolster its batting depth.`,
  },
  {
    name: 'Shivam Dube',
    image: '',
    born: 'June 26, 1993 (32 years)',
    birthPlace: 'Mumbai, Maharashtra',
    height: 'N/A',
    role: 'Allrounder',
    battingStyle: 'Left Handed Bat',
    bowlingStyle: 'Right arm Medium',
    team: 'Chennai Super Kings',
    summary: `Shivam Dube, the "Spin Assassin," continues to be CSK's most dangerous middle-order weapon. After his recent heroics at the T20 World Cup in March, his confidence is at an all-time high.\n\nIn 2026, his medium pace might see more usage due to the departure of Jadeja, making him a critical "dual-role" player who balances the side's composition.`,
  },
  {
    name: 'Prashant Veer',
    image: '',
    born: 'April 28, 2006 (19 years)',
    birthPlace: 'Uttar Pradesh',
    height: 'N/A',
    role: 'Bowling Allrounder',
    battingStyle: 'Left Handed Bat',
    bowlingStyle: 'Slow Left arm Orthodox',
    team: 'Chennai Super Kings',
    summary: `The headline of the 2026 auction, Veer was bought for a staggering ₹14.20 crore. As an uncapped all-rounder from Uttar Pradesh, he brings a high-velocity strike rate and useful left-arm orthodox spin.\n\nHis profile is that of a "modern-day utility player" who can finish games and bowl tough overs in the powerplay. All eyes will be on him to see if he can justify the record-breaking price tag.`,
  },
  {
    name: 'Matthew Short',
    image: '',
    born: 'April 14, 1996 (30 years)',
    birthPlace: 'Queensland, Australia',
    height: 'N/A',
    role: 'Batting Allrounder',
    battingStyle: 'Right Handed Bat',
    bowlingStyle: 'Right arm Offbreak',
    team: 'Chennai Super Kings',
    summary: `A versatile overseas acquisition, Short provides an explosive opening option and handy off-spin. Given the spin-friendly nature of Chennai, his ability to bowl in the powerplay while being a destructive force against the new ball makes him a tactical Swiss-army knife for Stephen Fleming.`,
  },
  {
    name: 'Jamie Overton',
    image: '',
    born: 'August 10, 1994 (31 years)',
    birthPlace: 'Barnstaple, England',
    height: 'N/A',
    role: 'Bowling Allrounder',
    battingStyle: 'Right Handed Bat',
    bowlingStyle: 'Right arm Fast',
    team: 'Chennai Super Kings',
    summary: `The tall Jamie Overton brings the "X-factor" of high pace and long-handle hitting. In a post-Sam Curran era, Overton is the designated overseas enforcer. His ability to extract bounce on tired pitches and hit towering sixes at No. 8 makes him a valuable asset for the death overs.`,
  },
  {
    name: 'Noor Ahmad',
    image: '',
    born: 'January 06, 2005 (20 years)',
    birthPlace: 'Kabul, Afghanistan',
    height: 'N/A',
    role: 'Bowler',
    battingStyle: 'Right Handed Bat',
    bowlingStyle: 'Left arm Wrist spin',
    team: 'Chennai Super Kings',
    summary: `The Afghan sensation is now the frontline overseas spinner for CSK. His left-arm wrist spin is nearly impossible to read under the lights at Chepauk. In 2026, Noor is expected to lead the spin attack, forming a lethal partnership with Rahul Chahar.`,
  },
  {
    name: 'Khaleel Ahmed',
    image: '',
    born: 'December 05, 1997 (27 years)',
    birthPlace: 'Tonk, Rajasthan',
    height: 'N/A',
    role: 'Bowler',
    battingStyle: 'Right Handed Bat',
    bowlingStyle: 'Left arm Fast medium',
    team: 'Chennai Super Kings',
    summary: `Retained for his ability to swing the ball both ways, Khaleel is the leader of the domestic pace battery. His left-arm angle is a traditional favourite for CSK tactics. In 2026, his primary role is to provide early breakthroughs. Improved death-bowling skills make him a reliable option for the final overs as well.`,
  },
  {
    name: 'Rahul Chahar',
    image: '',
    born: 'August 14, 1999 (26 years)',
    birthPlace: 'Agra, Uttar Pradesh',
    height: 'N/A',
    role: 'Bowler',
    battingStyle: 'Right Handed Bat',
    bowlingStyle: 'Legbreak Googly',
    team: 'Chennai Super Kings',
    summary: `Returning to the CSK setup via the auction, Chahar adds a proven wicket-taking leg-spin option. He knows the Indian conditions intimately and thrives on the pressure of the IPL. In 2026, he will be tasked with attacking the stumps and forcing batters into mistakes.`,
  },
  {
    name: 'Matt Henry',
    image: '',
    born: 'December 14, 1991 (33 years)',
    birthPlace: 'Christchurch, New Zealand',
    height: 'N/A',
    role: 'Bowler',
    battingStyle: 'Right Handed Bat',
    bowlingStyle: 'Right arm Fast medium',
    team: 'Chennai Super Kings',
    summary: `The Kiwi veteran is the perfect "Fleming-style" bowler—disciplined, accurate, and lethal with the moving ball. Henry provides a world-class alternative to the domestic pacers, especially in conditions that offer a bit of nip.`,
  },
  {
    name: 'Nathan Ellis',
    image: '',
    born: 'September 27, 1994 (31 years)',
    birthPlace: 'Queensland, Australia',
    height: 'N/A',
    role: 'Bowler',
    battingStyle: 'Right Handed Bat',
    bowlingStyle: 'Right arm Fast medium',
    team: 'Chennai Super Kings',
    summary: `The T20 specialist. Ellis is widely regarded as one of the best death bowlers in the world, with an array of cutters and a pinpoint yorker. In 2026, he is the designated "finisher" with the ball. When the game is on the line, Ellis is the player Gaikwad will turn to.`,
  },

  // ── DELHI CAPITALS ───────────────────────────────────────
  {
    name: 'KL Rahul',
    image: '',
    born: 'April 18, 1992 (33 years)',
    birthPlace: 'Mangalore, Karnataka',
    height: '6 ft 1 in',
    role: 'Wicketkeeper Batter',
    battingStyle: 'Right Handed Bat',
    bowlingStyle: '—',
    team: 'Delhi Capitals',
    summary: `After his much-debated exit from the Lucknow Super Giants, KL Rahul found his footing almost immediately at Delhi Capitals. A class act, KL Rahul brings a calming, methodical presence to the team's top order. Functioning as the classical anchor, his technical brilliance allows the explosive overseas contingent to play with utter freedom.\n\nAs a tactician and wicketkeeper, Rahul's acute understanding of match situations is paramount. His primary directive this season is to bat deep into the innings, ensuring DC's notoriously aggressive middle order has the ideal platform.`,
  },
  {
    name: 'Jake Fraser-McGurk',
    image: '',
    born: 'July 03, 2003 (22 years)',
    birthPlace: 'Melbourne, Australia',
    height: 'N/A',
    role: 'Top order Batter',
    battingStyle: 'Right Handed Bat',
    bowlingStyle: 'Right arm Offbreak',
    team: 'Delhi Capitals',
    summary: `The Australian dynamo returns to the Arun Jaitley Stadium as one of the most feared ball-strikers in global franchise cricket. Fraser-McGurk's modus operandi is simple: unadulterated aggression from the very first delivery. In IPL 2026, he is Delhi's designated powerplay enforcer.\n\nCapable of dismantling world-class pace attacks, the young Aussie with his extraordinary hand-eye coordination can send shivers down the opposition's spine.`,
  },
  {
    name: 'Harry Brook',
    image: '',
    born: 'February 22, 1999 (26 years)',
    birthPlace: 'Keighley, England',
    height: 'N/A',
    role: 'Batter',
    battingStyle: 'Right Handed Bat',
    bowlingStyle: 'Right arm Offbreak',
    team: 'Delhi Capitals',
    summary: `Harry Brook's inclusion adds a layer of sophisticated dynamism to the Capitals' engine room. The English maestro can be as destructive as anyone in this format and he can single-handedly take the team to victory from any situation, especially in a chase.\n\nHe is renowned for his 360-degree stroke play and an uncanny ability to effortlessly shift gears. DC will look to him to orchestrate the middle-over transitions.`,
  },
  {
    name: 'Tristan Stubbs',
    image: '',
    born: 'December 07, 1999 (25 years)',
    birthPlace: 'Cape Town, South Africa',
    height: 'N/A',
    role: 'Batter',
    battingStyle: 'Right Handed Bat',
    bowlingStyle: 'Right arm Offbreak',
    team: 'Delhi Capitals',
    summary: `On his day, he can be simply unstoppable. The South African prodigy has firmly established himself as a premier finisher in the T20 format. For DC in 2026, Stubbs is the linchpin of the middle order, possessing the rare ability to manipulate the field with deft sweeps before unleashing raw brute power.`,
  },
  {
    name: 'Axar Patel',
    image: '',
    born: 'January 20, 1994 (31 years)',
    birthPlace: 'Anand, Gujarat',
    height: 'N/A',
    role: 'Allrounder',
    battingStyle: 'Left Handed Bat',
    bowlingStyle: 'Slow Left arm Orthodox',
    team: 'Delhi Capitals',
    summary: `The skipper, Axar Patel has been the indispensable heartbeat of the Delhi Capitals. Axar's unerring accuracy with his left-arm orthodox spin makes him an absolute nightmare for batters on the gripping surfaces of Delhi.\n\nBeyond his bowling, Axar's metamorphosis into a reliable, hard-hitting lower-order batter provides DC with tremendous depth. For IPL 2026, his dual functionality is the cornerstone of their tactical blueprint.`,
  },
  {
    name: 'Kuldeep Yadav',
    image: '',
    born: 'December 14, 1994 (30 years)',
    birthPlace: 'Kanpur, Uttar Pradesh',
    height: 'N/A',
    role: 'Bowler',
    battingStyle: 'Left Handed Bat',
    bowlingStyle: 'Left arm Wrist spin',
    team: 'Delhi Capitals',
    summary: `India's premier left-arm wrist-spinner is the primary wicket-taking weapon in the Capitals' arsenal. Having completely reinvented his bowling mechanics, Kuldeep approaches IPL 2026 with increased pace, deceptive drift, and a lethal googly.\n\nOn the turning tracks of the Arun Jaitley Stadium, he forms a formidable 'Spin Twin' partnership with Axar Patel.`,
  },
  {
    name: 'Mitchell Starc',
    image: '',
    born: 'January 30, 1990 (35 years)',
    birthPlace: 'Baulkham Hills, Australia',
    height: '6 ft 4 in',
    role: 'Bowler',
    battingStyle: 'Left Handed Bat',
    bowlingStyle: 'Left arm Fast',
    team: 'Delhi Capitals',
    summary: `The marquee acquisition for the pace department, the towering Australian brings a wealth of pedigree and sheer terror to the DC bowling attack. Starc's mandate for IPL 2026 is brutally simple: shatter the stumps in the powerplay and execute unplayable yorkers at the death.`,
  },
  {
    name: 'T Natarajan',
    image: '',
    born: 'May 27, 1991 (34 years)',
    birthPlace: 'Salem, Tamil Nadu',
    height: 'N/A',
    role: 'Bowler',
    battingStyle: 'Left Handed Bat',
    bowlingStyle: 'Left arm Medium',
    team: 'Delhi Capitals',
    summary: `The 'Yorker King' from Tamil Nadu adds immense defensive stability to the Delhi Capitals' death-bowling strategies. Natarajan's repertoire is built upon relentless accuracy and an unparalleled ability to execute under extreme pressure.`,
  },
  {
    name: 'Mukesh Kumar',
    image: '',
    born: 'November 26, 1992 (32 years)',
    birthPlace: 'Bihar',
    height: 'N/A',
    role: 'Bowler',
    battingStyle: 'Right Handed Bat',
    bowlingStyle: 'Right arm Medium',
    team: 'Delhi Capitals',
    summary: `A testament to the grind of domestic cricket, Mukesh Kumar brings a blue-collar work ethic and unwavering discipline to the pace unit. For IPL 2026, Mukesh serves as the reliable domestic anchor in the seam department, often tasked with bowling the difficult transitional overs.`,
  },
  {
    name: 'Dushmantha Chameera',
    image: '',
    born: 'January 11, 1992 (33 years)',
    birthPlace: 'Sri Lanka',
    height: 'N/A',
    role: 'Bowler',
    battingStyle: 'Right Handed Bat',
    bowlingStyle: 'Right arm Fast',
    team: 'Delhi Capitals',
    summary: `The Sri Lankan speedster provides crucial overseas backup for the fast-bowling contingent. Known for his raw, skiddy pace and ability to hit the pitch hard, Chameera offers a different dimension to the DC attack.`,
  },

  // ── GUJARAT TITANS ───────────────────────────────────────
  {
    name: 'Shubman Gill',
    image: '',
    born: 'September 08, 1999 (26 years)',
    birthPlace: 'Fazilka, Punjab',
    height: '6 ft 0 in',
    role: 'Top order Batter',
    battingStyle: 'Right Handed Bat',
    bowlingStyle: 'Right arm Offbreak',
    team: 'Gujarat Titans',
    summary: `The captain of the Indian Test and ODI team, Shubman Gill will hold the reins of Gujarat Titans for another season in 2026. The 'Prince of Indian Cricket' continues to be the tactical and stylistic cornerstone of the Gujarat Titans.\n\nBlessed with impeccable timing and a technique that effortlessly dismantles both pace and spin, he provides the anchor around which the Titans' innings is constructed.`,
  },
  {
    name: 'Jos Buttler',
    image: '',
    born: 'September 08, 1990 (35 years)',
    birthPlace: 'Taunton, England',
    height: 'N/A',
    role: 'Wicketkeeper Batter',
    battingStyle: 'Right Handed Bat',
    bowlingStyle: '—',
    team: 'Gujarat Titans',
    summary: `The English white-ball colossus remains one of the most frightening prospects for any opening bowler. Having joined the Titans, Buttler's partnership with Gill creates a fascinating 'fire and ice' dynamic at the top. While Gill anchors, Buttler is given the absolute licence to obliterate the powerplay restrictions.`,
  },
  {
    name: 'Sai Sudharsan',
    image: '',
    born: 'February 19, 2002 (24 years)',
    birthPlace: 'Chennai, Tamil Nadu',
    height: 'N/A',
    role: 'Top order Batter',
    battingStyle: 'Left Handed Bat',
    bowlingStyle: 'Legbreak',
    team: 'Gujarat Titans',
    summary: `The elegant left-hander from Tamil Nadu has blossomed into the indispensable glue of the Gujarat Titans' batting lineup. Operating predominantly at number three, Sudharsan is the master of accumulating runs without taking unnecessary risks.\n\nHis supreme proficiency against spin makes him vital for navigating the treacherous middle overs, particularly on sluggish surfaces.`,
  },
  {
    name: 'Glenn Phillips',
    image: '',
    born: 'June 06, 1997 (28 years)',
    birthPlace: 'Auckland, New Zealand',
    height: 'N/A',
    role: 'Allrounder',
    battingStyle: 'Right Handed Bat',
    bowlingStyle: 'Right arm Offbreak',
    team: 'Gujarat Titans',
    summary: `The quintessential modern-day utility cricketer, the New Zealander brings an infectious, high-octane energy to the Titans' middle order. Glenn Phillips is a spectacular athlete, capable of turning the tide of a match with a breathtaking piece of fielding, a handy over of off-spin, or a blistering 20-ball cameo.`,
  },
  {
    name: 'M Shahrukh Khan',
    image: '',
    born: 'November 14, 1994 (30 years)',
    birthPlace: 'Chennai, Tamil Nadu',
    height: 'N/A',
    role: 'Batter',
    battingStyle: 'Right Handed Bat',
    bowlingStyle: 'Right arm Offbreak',
    team: 'Gujarat Titans',
    summary: `Retained to provide brute force in the lower-middle order, the formidable Tamil Nadu slugger is GT's designated death-overs enforcer. Shahrukh possesses a rare, unadulterated power game, specifically tailored to clear the boundary against both extreme pace and deceptive slower balls.`,
  },
  {
    name: 'Jason Holder',
    image: '',
    born: 'November 05, 1991 (34 years)',
    birthPlace: 'Bridgetown, Barbados',
    height: '6 ft 7 in',
    role: 'Bowling Allrounder',
    battingStyle: 'Right Handed Bat',
    bowlingStyle: 'Right arm Medium fast',
    team: 'Gujarat Titans',
    summary: `The marquee acquisition of the 2026 mini-auction, the towering West Indian is the tactical puzzle piece that completes the GT jigsaw. Holder provides immense structural balance, functioning as a high-quality seam option who extracts steep bounce, whilst also offering crucial batting depth.`,
  },
  {
    name: 'Washington Sundar',
    image: '',
    born: 'October 02, 1999 (26 years)',
    birthPlace: 'Chennai, Tamil Nadu',
    height: 'N/A',
    role: 'Bowling Allrounder',
    battingStyle: 'Left Handed Bat',
    bowlingStyle: 'Right arm Offbreak',
    team: 'Gujarat Titans',
    summary: `The tall, elegant off-spinner provides GT with vital match-up advantages and powerplay control. Washington's unerring accuracy and ability to skid the ball into the right-handers make him a highly economical option. Furthermore, his evolution as a genuinely capable left-handed batter adds a crucial dimension to the lower-middle order.`,
  },
  {
    name: 'Rahul Tewatia',
    image: '',
    born: 'September 22, 1993 (32 years)',
    birthPlace: 'Faridabad, Haryana',
    height: 'N/A',
    role: 'Bowling Allrounder',
    battingStyle: 'Left Handed Bat',
    bowlingStyle: 'Legbreak',
    team: 'Gujarat Titans',
    summary: `The 'Iceman' of the Indian Premier League. Tewatia's legacy at the Gujarat Titans is built upon a foundation of impossible run chases and final-over heroics. In IPL 2026, Tewatia's role is incredibly defined: absorb extreme pressure and deliver when the required run rate skyrockets.`,
  },
  {
    name: 'Rashid Khan',
    image: '',
    born: 'September 20, 1998 (27 years)',
    birthPlace: 'Nangarhar, Afghanistan',
    height: 'N/A',
    role: 'Bowling Allrounder',
    battingStyle: 'Right Handed Bat',
    bowlingStyle: 'Legbreak Googly',
    team: 'Gujarat Titans',
    summary: `The Afghan maestro remains the undisputed crown jewel of the GT bowling attack. Rashid is not merely a bowler but a spin wizard who can bring any batting line-up to their knees. His mesmerising arm speed and an unreadable googly make him the ultimate defensive and attacking weapon combined.`,
  },
  {
    name: 'Kagiso Rabada',
    image: '',
    born: 'May 25, 1995 (30 years)',
    birthPlace: 'Johannesburg, South Africa',
    height: 'N/A',
    role: 'Bowler',
    battingStyle: 'Left Handed Bat',
    bowlingStyle: 'Right arm Fast',
    team: 'Gujarat Titans',
    summary: `The South African speedster anchors a terrifying pace battery for the Titans. Rabada brings sheer, unadulterated hostility and world-class pedigree to the franchise. His ability to consistently clock speeds north of 145 km/h makes him a formidable weapon on any surface.`,
  },
  {
    name: 'Mohammed Siraj',
    image: '',
    born: 'March 13, 1994 (31 years)',
    birthPlace: 'Hyderabad, Telangana',
    height: 'N/A',
    role: 'Bowler',
    battingStyle: 'Right Handed Bat',
    bowlingStyle: 'Right arm Fast',
    team: 'Gujarat Titans',
    summary: `The fiery Indian spearhead perfectly complements Rabada's hostility with relentless energy and lethal new-ball swing. Siraj has mastered the art of the wobble-seam delivery, making him incredibly difficult to line up in the powerplay.`,
  },
  {
    name: 'Prasidh Krishna',
    image: '',
    born: 'February 19, 1996 (29 years)',
    birthPlace: 'Bangalore, Karnataka',
    height: '6 ft 2 in',
    role: 'Bowler',
    battingStyle: 'Right Handed Bat',
    bowlingStyle: 'Right arm Fast medium',
    team: 'Gujarat Titans',
    summary: `Standing tall and extracting disconcerting bounce from even the most docile pitches, Prasidh Krishna adds a unique dimension to the GT pace attack. His ability to hit the deck hard and rush the batters makes him an exceptional enforcer during the middle overs.`,
  },
  {
    name: 'Sai Kishore',
    image: '',
    born: 'April 21, 1996 (29 years)',
    birthPlace: 'Chennai, Tamil Nadu',
    height: 'N/A',
    role: 'Bowler',
    battingStyle: 'Left Handed Bat',
    bowlingStyle: 'Slow Left arm Orthodox',
    team: 'Gujarat Titans',
    summary: `The lanky left-arm orthodox spinner is the quiet, unassuming hero of the GT attack. Sai Kishore thrives on immaculate control and an innate understanding of his own limitations. He is the holding bowler, tasked with bowling dry, economical spells that force the batters to take risks against the strike bowlers.`,
  },
  {
    name: 'Ishant Sharma',
    image: '',
    born: 'September 02, 1988 (37 years)',
    birthPlace: 'Delhi',
    height: '6 ft 4 in',
    role: 'Bowler',
    battingStyle: 'Right Handed Bat',
    bowlingStyle: 'Right arm Fast medium',
    team: 'Gujarat Titans',
    summary: `The seasoned veteran brings a wealth of experience and nuanced skill to the GT pace rotation. Having reinvented himself as a T20 specialist, Ishant's value lies in his towering height and ability to seam the ball off the pitch. His calm demeanour and tactical nous make him a brilliant mentor for the younger quicks.`,
  },
  {
    name: 'Tom Banton',
    image: '',
    born: 'November 11, 1998 (27 years)',
    birthPlace: 'Bristol, England',
    height: 'N/A',
    role: 'Wicketkeeper Batter',
    battingStyle: 'Right Handed Bat',
    bowlingStyle: '—',
    team: 'Gujarat Titans',
    summary: `The dynamic English opener was acquired at the 2026 auction to provide elite overseas cover. Known for his 360-degree innovation and audacious reverse sweeps, Banton is a highly disruptive force at the top of the order. In 2026, expect him to be heavily involved if GT wishes to alter their tempo.`,
  },

  // ── ROYAL CHALLENGERS BENGALURU ─────────────────────────
  {
    name: 'Virat Kohli',
    image: '',
    born: 'November 05, 1988 (37 years)',
    birthPlace: 'Delhi',
    height: '5 ft 9 in (175 cm)',
    role: 'Batter',
    battingStyle: 'Right Handed Bat',
    bowlingStyle: 'Right arm Medium',
    team: 'Royal Challengers Bengaluru',
    summary: `A spunky, chubby teenager with gelled hair shot to fame after leading India to glory in the Under-19 World Cup at Kuala Lumpur in early 2008. In an Indian team filled with saint-like icons worthy of their own hagiographies, Virat Kohli, with his most un-Indian, 'bad-boy' intensity, would clearly be an outcast.\n\nYet, over the course of his career, Kohli transformed himself into one of cricket's all-time greats. The pride of Royal Challengers Bengaluru, his passion for the game, intensity on the field, and run-scoring consistency are unmatched. In IPL 2026, Kohli remains RCB's talisman and the heartbeat of their batting lineup, the one player every opponent plans around.`,
  },
  {
    name: 'Rajat Patidar',
    image: '',
    born: 'June 01, 1993 (31 years)',
    birthPlace: 'Indore, Madhya Pradesh',
    height: 'N/A',
    role: 'Batter',
    battingStyle: 'Right Handed Bat',
    bowlingStyle: 'Right arm Offbreak',
    team: 'Royal Challengers Bengaluru',
    summary: `Rajat Patidar is the captain of Royal Challengers Bengaluru for IPL 2026. His maiden IPL century against LSG in the 2022 Qualifier 2 announced him on the big stage, and he has not looked back since. An aggressive right-hander, he is particularly devastating against spin and thrives in high-pressure situations.`,
  },

  // ── MUMBAI INDIANS ───────────────────────────────────────
  {
    name: 'Rohit Sharma',
    image: '',
    born: 'April 30, 1987 (38 years)',
    birthPlace: 'Bansod, Nagpur, Maharashtra',
    height: '5 ft 8 in',
    role: 'Opening Batter',
    battingStyle: 'Right Handed Bat',
    bowlingStyle: 'Right arm Offbreak',
    team: 'Mumbai Indians',
    summary: `The Hitman. Rohit Sharma is the soul of Mumbai Indians and one of the most successful captains in IPL history. A master of the ramp, pull, and square cut, his ability to play both the anchor and aggressor role makes him invaluable.\n\nIn IPL 2026, Rohit's experience and calm demeanour will be crucial in guiding a young MI side through the gruelling tournament.`,
  },
  {
    name: 'Jasprit Bumrah',
    image: '',
    born: 'December 06, 1993 (31 years)',
    birthPlace: 'Ahmedabad, Gujarat',
    height: '6 ft 0 in',
    role: 'Bowler',
    battingStyle: 'Right Handed Bat',
    bowlingStyle: 'Right arm Fast medium',
    team: 'Mumbai Indians',
    summary: `The best bowler in the world, Jasprit Bumrah is the ultimate weapon for Mumbai Indians. His unorthodox bowling action, combined with deadly accuracy and the ability to bowl unplayable yorkers at will, makes him nearly impossible to score off in death overs.\n\nIn IPL 2026, Bumrah is the spearhead of the MI pace attack and one of the key players who can win matches single-handedly.`,
  },
  {
    name: 'Suryakumar Yadav',
    image: '',
    born: 'September 22, 1990 (34 years)',
    birthPlace: 'Mumbai, Maharashtra',
    height: '5 ft 9 in',
    role: 'Batter',
    battingStyle: 'Right Handed Bat',
    bowlingStyle: 'Right arm Medium',
    team: 'Mumbai Indians',
    summary: `The 360-degree batsman, Suryakumar Yadav is one of the most exciting cricketers in the world today. Ranked consistently as the top T20I batter, his ability to play shots all around the ground, including the audacious scoop and ramp, makes him a nightmare for any bowling attack.\n\nIn IPL 2026, SKY is expected to be the main enforcer in Mumbai's middle order.`,
  },
  {
    name: 'Hardik Pandya',
    image: '',
    born: 'October 11, 1993 (31 years)',
    birthPlace: 'Surat, Gujarat',
    height: '6 ft 1 in',
    role: 'Allrounder',
    battingStyle: 'Right Handed Bat',
    bowlingStyle: 'Right arm Fast medium',
    team: 'Mumbai Indians',
    summary: `The 'All-Action Hero', Hardik Pandya returns to lead Mumbai Indians after his stint as captain. A genuine match-winner with both bat and ball, Hardik's explosive lower-order hitting and ability to bowl quick spells at over 140 km/h make him one of the most valuable players in T20 cricket. In 2026, he is expected to contribute heavily in crunch situations.`,
  },

  // ── RAJASTHAN ROYALS ─────────────────────────────────────
  {
    name: 'Yashasvi Jaiswal',
    image: '',
    born: 'December 28, 2001 (23 years)',
    birthPlace: 'Suriyawan, Uttar Pradesh',
    height: '5 ft 11 in',
    role: 'Opening Batter',
    battingStyle: 'Left Handed Bat',
    bowlingStyle: 'Slow Left arm Orthodox',
    team: 'Rajasthan Royals',
    summary: `The pocket dynamo from Uttar Pradesh, Yashasvi Jaiswal has established himself as one of the most exciting young batters in world cricket. His audacious strokeplay, combined with a solid defensive technique, makes him a class act at the top of the order.\n\nIn IPL 2026, Jaiswal is Rajasthan Royals' go-to man for big powerplay scores and a potential Orange Cap contender.`,
  },
  {
    name: 'Riyan Parag',
    image: '',
    born: 'November 10, 2001 (23 years)',
    birthPlace: 'Guwahati, Assam',
    height: 'N/A',
    role: 'Batter',
    battingStyle: 'Right Handed Bat',
    bowlingStyle: 'Right arm Offbreak',
    team: 'Rajasthan Royals',
    summary: `The young warrior from Assam, Riyan Parag has blossomed into a key middle-order asset for Rajasthan Royals. Known for his aggressive batting style and match-winning performances, Parag's ability to play both anchor and aggressor roles adds great depth to the Royals' batting lineup.`,
  },
  {
    name: 'Ravindra Jadeja',
    image: '',
    born: 'December 06, 1988 (36 years)',
    birthPlace: 'Nawanagar, Gujarat',
    height: '5 ft 11 in',
    role: 'Allrounder',
    battingStyle: 'Left Handed Bat',
    bowlingStyle: 'Slow Left arm Orthodox',
    team: 'Rajasthan Royals',
    summary: `Sir Jadeja, the legendary all-rounder, joins Rajasthan Royals for IPL 2026. His accurate left-arm spin, explosive lower-order batting, and exceptional fielding make him one of the most complete cricketers in the world. His experience will be invaluable for the Royals' campaign.`,
  },

  // ── KOLKATA KNIGHT RIDERS ───────────────────────────────
  {
    name: 'Ajinkya Rahane',
    image: '',
    born: 'June 06, 1988 (37 years)',
    birthPlace: 'Ashwi Khurd, Maharashtra',
    height: '5 ft 8 in',
    role: 'Top order Batter',
    battingStyle: 'Right Handed Bat',
    bowlingStyle: 'Right arm Medium',
    team: 'Kolkata Knight Riders',
    summary: `The veteran captain Ajinkya Rahane leads Kolkata Knight Riders into IPL 2026. Known for his composed temperament and ability to build innings, Rahane's experience in high-pressure situations makes him a dependable leader. His classical batting style combined with smart cricketing brain makes him an astute tactical choice to lead KKR.`,
  },
  {
    name: 'Sunil Narine',
    image: '',
    born: 'May 26, 1988 (37 years)',
    birthPlace: 'Arima, Trinidad',
    height: 'N/A',
    role: 'Bowling Allrounder',
    battingStyle: 'Left Handed Bat',
    bowlingStyle: 'Right arm Offbreak',
    team: 'Kolkata Knight Riders',
    summary: `The mystery spinner and pinch-hitter extraordinaire, Sunil Narine has been KKR's most valuable player for many seasons. His ability to open the batting with explosive intent while bowling tight, unreadable spells in the middle overs makes him the ultimate dual-threat weapon in T20 cricket.`,
  },
  {
    name: 'Rinku Singh',
    image: '',
    born: 'October 12, 1997 (28 years)',
    birthPlace: 'Aligarh, Uttar Pradesh',
    height: 'N/A',
    role: 'Middle order Batter',
    battingStyle: 'Left Handed Bat',
    bowlingStyle: 'Right arm Offbreak',
    team: 'Kolkata Knight Riders',
    summary: `The 'Aligarh Express', Rinku Singh has become one of the most feared finishers in T20 cricket. His ability to hit sixes at will in the death overs—regardless of the required run rate—has made him a fan favourite and a match-winner for KKR. In IPL 2026, Rinku is expected to continue his role as the ultimate pressure-situation batter.`,
  },
  {
    name: 'Varun Chakravarthy',
    image: '',
    born: 'August 29, 1991 (34 years)',
    birthPlace: 'Chennai, Tamil Nadu',
    height: 'N/A',
    role: 'Bowler',
    battingStyle: 'Right Handed Bat',
    bowlingStyle: 'Legbreak Googly',
    team: 'Kolkata Knight Riders',
    summary: `The mystery spinner from Tamil Nadu, Varun Chakravarthy's unreadable variations have troubled the best batters in the world. His ability to bowl different deliveries without changing his action makes him a potent middle-overs weapon for KKR. In IPL 2026, he is expected to be the primary wicket-taker for the Knights.`,
  },

  // ── LUCKNOW SUPER GIANTS ─────────────────────────────────
  {
    name: 'Rishabh Pant',
    image: '',
    born: 'October 04, 1997 (28 years)',
    birthPlace: 'Roorkee, Uttarakhand',
    height: '5 ft 7 in',
    role: 'Wicketkeeper Batter',
    battingStyle: 'Left Handed Bat',
    bowlingStyle: '—',
    team: 'Lucknow Super Giants',
    summary: `The unstoppable Rishabh Pant leads Lucknow Super Giants in IPL 2026. One of the most entertaining cricketers in the world, Pant's audacious strokeplay and ability to change the game in a matter of overs makes him the ultimate match-winner. As captain, his fearless approach and bold decision-making adds an exciting dimension to the LSG campaign.`,
  },
  {
    name: 'Mohammed Shami',
    image: '',
    born: 'September 03, 1990 (35 years)',
    birthPlace: 'Amroha, Uttar Pradesh',
    height: '5 ft 11 in',
    role: 'Bowler',
    battingStyle: 'Right Handed Bat',
    bowlingStyle: 'Right arm Fast medium',
    team: 'Lucknow Super Giants',
    summary: `The master of swing and seam, Mohammed Shami brings world-class credentials to Lucknow Super Giants' pace attack. His ability to extract movement in both directions, combined with a sharp bouncer and a lethal yorker, makes him one of the best pacers in the world. In IPL 2026, Shami is expected to be the leader of the LSG bowling attack.`,
  },
  {
    name: 'Mayank Yadav',
    image: '',
    born: 'June 10, 2002 (23 years)',
    birthPlace: 'Delhi',
    height: 'N/A',
    role: 'Bowler',
    battingStyle: 'Right Handed Bat',
    bowlingStyle: 'Right arm Fast',
    team: 'Lucknow Super Giants',
    summary: `The speed sensation, Mayank Yadav burst onto the IPL scene with thunderbolt deliveries regularly clocking above 155 km/h. Despite his age, his raw pace and ability to hit hard lengths make him one of the most exciting pace talents in world cricket. Fitness permitting, he is a guaranteed match-winner for LSG.`,
  },
  {
    name: 'Nicholas Pooran',
    image: '',
    born: 'October 02, 1995 (30 years)',
    birthPlace: 'Couva, Trinidad',
    height: '5 ft 8 in',
    role: 'Wicketkeeper Batter',
    battingStyle: 'Left Handed Bat',
    bowlingStyle: '—',
    team: 'Lucknow Super Giants',
    summary: `The West Indian power-hitter, Nicholas Pooran is one of the most dangerous batters in T20 cricket. His ability to clear the boundary with the minimum of effort, combined with elite wicketkeeping skills, makes him a hugely valuable asset for Lucknow Super Giants. In IPL 2026, Pooran is expected to be a key run-scorer and a potential match-winner.`,
  },

  // ── PUNJAB KINGS ─────────────────────────────────────────
  {
    name: 'Shreyas Iyer',
    image: '',
    born: 'December 06, 1994 (30 years)',
    birthPlace: 'Mumbai, Maharashtra',
    height: '5 ft 11 in',
    role: 'Batter',
    battingStyle: 'Right Handed Bat',
    bowlingStyle: 'Right arm Offbreak',
    team: 'Punjab Kings',
    summary: `The stylish middle-order batter and captain, Shreyas Iyer leads Punjab Kings for IPL 2026. Known for his aggressive but technically sound batting, Iyer is particularly devastating against short-pitched bowling. His leadership experience across multiple franchises adds invaluable tactical know-how to PBKS' campaign.`,
  },
  {
    name: 'Arshdeep Singh',
    image: '',
    born: 'February 05, 2000 (25 years)',
    birthPlace: 'Gidderbaha, Punjab',
    height: '6 ft 1 in',
    role: 'Bowler',
    battingStyle: 'Left Handed Bat',
    bowlingStyle: 'Left arm Fast medium',
    team: 'Punjab Kings',
    summary: `The local hero from Punjab, Arshdeep Singh has established himself as one of India's premier T20 bowlers. His ability to bowl tight death overs with pinpoint yorkers and slower balls makes him invaluable for Punjab Kings. In IPL 2026, Arshdeep is the leader of the PBKS pace attack and a key wicket-taker.`,
  },
  {
    name: 'Yuzvendra Chahal',
    image: '',
    born: 'July 23, 1990 (35 years)',
    birthPlace: 'Jind, Haryana',
    height: '5 ft 6 in',
    role: 'Bowler',
    battingStyle: 'Right Handed Bat',
    bowlingStyle: 'Legbreak Googly',
    team: 'Punjab Kings',
    summary: `The leg-spin wizard, Yuzvendra Chahal is India's most successful T20I bowler and a proven wicket-taker in the IPL. His ability to flight the ball, generate turn, and deceive batters with his googly makes him a major weapon on responsive pitches. In IPL 2026, Chahal is expected to be Punjab Kings' primary spin threat.`,
  },

  // ── SUNRISERS HYDERABAD ──────────────────────────────────
  {
    name: 'Travis Head',
    image: '',
    born: 'December 29, 1993 (31 years)',
    birthPlace: 'Adelaide, Australia',
    height: '5 ft 11 in',
    role: 'Opening Batter',
    battingStyle: 'Left Handed Bat',
    bowlingStyle: 'Right arm Offbreak',
    team: 'Sunrisers Hyderabad',
    summary: `The Australian powerplay destroyer, Travis Head is one of the most devastating openers in T20 cricket. His ability to take the attack to any bowling attack from the first ball, combined with his ability to play both aggressively and sensibly, makes him a huge asset for Sunrisers Hyderabad.\n\nIn IPL 2026, Head is expected to be one of the top run-scorers and set the tone for SRH's batting.`,
  },
  {
    name: 'Pat Cummins',
    image: '',
    born: 'May 08, 1993 (32 years)',
    birthPlace: 'Westmead, Australia',
    height: '6 ft 3 in',
    role: 'Bowler',
    battingStyle: 'Right Handed Bat',
    bowlingStyle: 'Right arm Fast medium',
    team: 'Sunrisers Hyderabad',
    summary: `The Australian Test captain, Pat Cummins adds world-class credentials to the Sunrisers Hyderabad bowling attack. His ability to bowl fast, accurate spells with both new and old ball, combined with his late-order batting ability, makes him a complete cricketer. In IPL 2026, Cummins is the leader of SRH's pace attack.`,
  },
  {
    name: 'Heinrich Klaasen',
    image: '',
    born: 'July 30, 1991 (33 years)',
    birthPlace: 'Pretoria, South Africa',
    height: 'N/A',
    role: 'Wicketkeeper Batter',
    battingStyle: 'Right Handed Bat',
    bowlingStyle: '—',
    team: 'Sunrisers Hyderabad',
    summary: `The South African power-hitter, Heinrich Klaasen is one of the most dangerous death-over batters in world cricket. His ability to hit any bowler over any boundary, combined with sharp wicketkeeping, makes him invaluable for SRH. In IPL 2026, Klaasen is expected to be the key finisher in the SRH batting order.`,
  },
  {
    name: 'Abhishek Sharma',
    image: '',
    born: 'September 04, 2000 (24 years)',
    birthPlace: 'Amritsar, Punjab',
    height: 'N/A',
    role: 'Allrounder',
    battingStyle: 'Left Handed Bat',
    bowlingStyle: 'Slow Left arm Orthodox',
    team: 'Sunrisers Hyderabad',
    summary: `The explosive young opener, Abhishek Sharma has been one of the breakout stars of recent IPL seasons. His ability to hit towering sixes from the first ball, combined with useful left-arm spin, makes him a genuine all-round threat for SRH. In IPL 2026, he is expected to be a key contributor at the top of the order.`,
  },
  {
    name: 'Nitish Kumar Reddy',
    image: '',
    born: 'January 04, 2004 (22 years)',
    birthPlace: 'Hyderabad, Telangana',
    height: 'N/A',
    role: 'Allrounder',
    battingStyle: 'Right Handed Bat',
    bowlingStyle: 'Right arm Fast medium',
    team: 'Sunrisers Hyderabad',
    summary: `The young Hyderabad sensation, Nitish Kumar Reddy is one of the most exciting young talents in Indian cricket. His explosive hitting in the lower-middle order, combined with his ability to bowl useful medium-pace spells, makes him a genuine all-rounder. In IPL 2026, he is expected to continue his rise as one of SRH's key players.`,
  },
  {
    name: 'Ishan Kishan',
    image: '',
    born: 'July 18, 1998 (27 years)',
    birthPlace: 'Patna, Bihar',
    height: '5 ft 7 in',
    role: 'Wicketkeeper Batter',
    battingStyle: 'Left Handed Bat',
    bowlingStyle: '—',
    team: 'Sunrisers Hyderabad',
    summary: `The powerful left-handed opener, Ishan Kishan brings explosive batting and sharp wicketkeeping to Sunrisers Hyderabad. Known for his ability to hit big sixes and set the tone for big totals, Kishan is a perfect fit for SRH's aggressive batting philosophy. In IPL 2026, he is expected to form a dangerous opening partnership with Travis Head.`,
  },
]