// src/shared/data/cricketNews.data.js

export const cricketNewsData = [
  {
    id: 'cn-1',
    slug: 'india-women-tour-australia-day1',
    title: 'India Women Tour of Australia — Day 1 Highlights & Review',
    description:
      'India Women posted a commanding 184/8 in their first innings on Day 1 of the Test match against Australia Women at the WACA. Smriti Mandhana led the batting with a sublime 72, while Deepti Sharma chipped in with a crucial 38 at the lower order. Australian spinner Tahlia McGrath was the pick of the bowlers, claiming 3 wickets for 42 runs.',
    image: 'https://images.unsplash.com/photo-1531415074968-036ba1b575da?w=800&q=80',
    category: 'Cricket',
    subCategory: 'Test',
    source: 'CricInfo',
    author: 'Sidharth Monga',
    time: '2h ago',
    date: '2025-03-23T08:00:00Z',
    series: 'India Women Tour of Australia 2025',
    venue: 'WACA, Perth',
    tags: ['India Women', 'Australia Women', 'Test Cricket', 'WACA'],
  },
  {
    id: 'cn-2',
    slug: 'rohit-sharma-form-concern',
    title: "Rohit Sharma's lean patch raises concern ahead of Champions Trophy",
    description:
      'India captain Rohit Sharma has managed just 67 runs in his last five ODI innings, sparking widespread debate about his form ahead of the ICC Champions Trophy. Selectors are reportedly keeping a close watch, with young openers waiting in the wings. However, head coach Gautam Gambhir has publicly backed the skipper to come good.',
    image: 'https://images.unsplash.com/photo-1540747913346-19e32dc3e97e?w=800&q=80',
    category: 'Cricket',
    subCategory: 'ODI',
    source: 'The Hindu',
    author: 'R Kaushik',
    time: '3h ago',
    date: '2025-03-23T07:00:00Z',
    series: 'ICC Champions Trophy 2025',
    venue: 'Various',
    tags: ['Rohit Sharma', 'India', 'Champions Trophy', 'Form'],
  },
  {
    id: 'cn-3',
    slug: 'ipl-2025-mega-auction-recap',
    title: 'IPL 2025 Mega Auction: Who won the bidding war?',
    description:
      'The IPL 2025 Mega Auction concluded with record-breaking bids across multiple categories. Mitchell Starc became the most expensive overseas player at ₹24.75 crore, while Yashasvi Jaiswal fetched ₹18 crore from Rajasthan Royals. We break down every franchise\'s strategy, hits, misses, and overall squad depth heading into the new season.',
    image: 'https://images.unsplash.com/photo-1461896836934-ffe607ba8211?w=800&q=80',
    category: 'Cricket',
    subCategory: 'T20',
    source: 'ESPNcricinfo',
    author: 'Gaurav Kalra',
    time: '5h ago',
    date: '2025-03-23T05:00:00Z',
    series: 'IPL 2025',
    venue: 'Various',
    tags: ['IPL', 'Auction', 'T20', 'BCCI'],
  },
  {
    id: 'cn-4',
    slug: 'bumrah-injury-update',
    title: 'Jasprit Bumrah given green light ahead of Champions Trophy opener',
    description:
      'Indian pace ace Jasprit Bumrah has been cleared to play after undergoing back scans that came back clear. The BCCI medical team confirmed he is fit for selection and will participate in the first warm-up game against New Zealand next week. His inclusion is a massive boost for India\'s Champions Trophy campaign.',
    image: 'https://images.unsplash.com/photo-1508098682722-e99c43a406b2?w=800&q=80',
    category: 'Cricket',
    subCategory: 'ODI',
    source: 'BCCI Official',
    author: 'Press Release',
    time: '6h ago',
    date: '2025-03-23T04:00:00Z',
    series: 'ICC Champions Trophy 2025',
    venue: 'Dubai',
    tags: ['Bumrah', 'India', 'Injury Update', 'Champions Trophy'],
  },
  {
    id: 'cn-5',
    slug: 'australia-squad-announced-ashes',
    title: 'Australia announce 15-man squad for Ashes series opener',
    description:
      'Cricket Australia has unveiled the 15-man squad for the first Ashes Test at Edgbaston. David Warner returns from retirement for one final Test, while Cameron Green earns a recall after recovering from a finger injury. Josh Hazlewood remains rested as a precautionary measure for the long series.',
    image: 'https://images.unsplash.com/photo-1536183922588-166604504d5e?w=800&q=80',
    category: 'Cricket',
    subCategory: 'Test',
    source: 'Cricket Australia',
    author: 'Adam Collins',
    time: '8h ago',
    date: '2025-03-23T02:00:00Z',
    series: 'The Ashes 2025',
    venue: 'Edgbaston, Birmingham',
    tags: ['Australia', 'Ashes', 'Test Cricket', 'Squad'],
  },
  {
    id: 'cn-6',
    slug: 'sa20-final-preview',
    title: 'SA20 Final Preview: Sunrisers Eastern Cape vs MI Cape Town',
    description:
      'Two powerhouse franchises clash in the SA20 final at Newlands. Sunrisers Eastern Cape, powered by Heinrich Klaasen\'s explosive batting and Alzarri Joseph\'s pace, face MI Cape Town who boast Liam Livingstone and Rashid Khan in their ranks. We preview the key matchups, pitch report, and predicted XIs.',
    image: 'https://images.unsplash.com/photo-1554143091-c41d76e5a2a9?w=800&q=80',
    category: 'Cricket',
    subCategory: 'T20',
    source: 'Cricket South Africa',
    author: 'Neil Manthorp',
    time: '9h ago',
    date: '2025-03-23T01:00:00Z',
    series: 'SA20 2025',
    venue: 'Newlands, Cape Town',
    tags: ['SA20', 'T20', 'South Africa', 'Final'],
  },
  {
    id: 'cn-7',
    slug: 'england-bazball-evolution',
    title: "England's Bazball 2.0: How they've evolved under Stokes and McCullum",
    description:
      'Two years into the Stokes-McCullum era, England have transformed Test cricket with their aggressive brand of play. Data shows they score at 4.2 runs per over in Tests — the highest of any top-8 nation. We analyse the tactical evolution, statistical impact, and whether the approach is sustainable against elite bowling attacks.',
    image: 'https://images.unsplash.com/photo-1486286701208-1d58e9338013?w=800&q=80',
    category: 'Cricket',
    subCategory: 'Test',
    source: 'The Cricket Monthly',
    author: 'Jarrod Kimber',
    time: '10h ago',
    date: '2025-03-23T00:00:00Z',
    series: 'General',
    venue: 'Various',
    tags: ['England', 'Bazball', 'Test Cricket', 'Ben Stokes'],
  },
  {
    id: 'cn-8',
    slug: 'wpl-2025-opening-ceremony',
    title: "WPL 2025 Opening Ceremony: Women's cricket gets star-studded launch",
    description:
      "The Women's Premier League 2025 kicked off with a spectacular opening ceremony in Mumbai, attended by BCCI officials, Bollywood celebrities, and cricket legends. Defending champions Mumbai Indians will face Delhi Capitals in the tournament opener, promising high-octane T20 action across five franchises.",
    image: 'https://images.unsplash.com/photo-1431324155629-1a6deb1dec8d?w=800&q=80',
    category: 'Cricket',
    subCategory: 'T20',
    source: 'BCCI Official',
    author: 'Press Release',
    time: '12h ago',
    date: '2025-03-22T22:00:00Z',
    series: 'WPL 2025',
    venue: 'Wankhede Stadium, Mumbai',
    tags: ["Women's Cricket", 'WPL', 'T20', 'India'],
  },
]