// src/shared/data/footballNews.data.js

export const footballNewsData = [
  {
    id: 'fn-1',
    slug: 'arsenal-chelsea-premier-league-thriller',
    title: 'Arsenal vs Chelsea: Premier League Thriller Ends 2-1 at Emirates',
    description:
      "Arsenal secured a crucial three points in the title race with a gritty 2-1 victory over London rivals Chelsea at the Emirates. Bukayo Saka opened the scoring with a stunning long-range effort in the 23rd minute, before Gabriel Martinelli doubled the lead. Cole Palmer's late consolation for Chelsea set up a nervous finale but Arsenal held on.",
    image: 'https://images.unsplash.com/photo-1431324155629-1a6deb1dec8d?w=800&q=80',
    category: 'Football',
    subCategory: 'Premier League',
    source: 'BBC Sport',
    author: 'Phil McNulty',
    time: '1h ago',
    date: '2025-03-23T09:30:00Z',
    league: 'Premier League',
    venue: 'Emirates Stadium, London',
    tags: ['Arsenal', 'Chelsea', 'Premier League', 'London Derby'],
  },
  {
    id: 'fn-2',
    slug: 'barcelona-real-madrid-clasico-preview',
    title: 'El Clásico Preview: Barcelona vs Real Madrid — The title decider?',
    description:
      'Saturday\'s El Clásico at Camp Nou could prove to be the decisive moment in the La Liga title race. Barcelona lead Real Madrid by just two points with ten games remaining. Lamine Yamal is fit for the hosts after recovering from a knock, while Kylian Mbappé carries the attacking threat for the visitors. Tactical breakdown, predicted XIs, and key battles inside.',
    image: 'https://images.unsplash.com/photo-1508098682722-e99c43a406b2?w=800&q=80',
    category: 'Football',
    subCategory: 'La Liga',
    source: 'Marca',
    author: 'Diego Torres',
    time: '2h ago',
    date: '2025-03-23T08:30:00Z',
    league: 'La Liga',
    venue: 'Camp Nou, Barcelona',
    tags: ['Barcelona', 'Real Madrid', 'El Clasico', 'La Liga'],
  },
  {
    id: 'fn-3',
    slug: 'champions-league-quarter-final-draw',
    title: 'UEFA Champions League QF Draw: Man City vs PSG headline tie',
    description:
      'The UEFA Champions League quarter-final draw produced a blockbuster fixture as Manchester City were paired with Paris Saint-Germain. Real Madrid will face Borussia Dortmund in a rematch of last season\'s final, while Bayern Munich take on Inter Milan and Arsenal meet Atletico Madrid in the other ties.',
    image: 'https://images.unsplash.com/photo-1566577739112-5180d4bf9390?w=800&q=80',
    category: 'Football',
    subCategory: 'Champions League',
    source: 'UEFA Official',
    author: 'Press Release',
    time: '3h ago',
    date: '2025-03-23T07:30:00Z',
    league: 'UEFA Champions League',
    venue: 'UEFA HQ, Nyon',
    tags: ['Champions League', 'Man City', 'PSG', 'Draw'],
  },
  {
    id: 'fn-4',
    slug: 'mbappe-injury-scare-real-madrid',
    title: "Mbappé injury scare: Real Madrid sweat on striker's fitness",
    description:
      "Kylian Mbappé limped off during Real Madrid's training session on Thursday, sparking major concern ahead of the El Clásico weekend. Club physios are monitoring a tight hamstring, and the French striker faces a fitness test on Friday morning. Madrid boss Carlo Ancelotti refused to confirm or deny his availability.",
    image: 'https://images.unsplash.com/photo-1486286701208-1d58e9338013?w=800&q=80',
    category: 'Football',
    subCategory: 'La Liga',
    source: 'AS',
    author: 'Tomas Roncero',
    time: '4h ago',
    date: '2025-03-23T06:30:00Z',
    league: 'La Liga',
    venue: 'Valdebebas Training Ground, Madrid',
    tags: ['Mbappe', 'Real Madrid', 'Injury', 'La Liga'],
  },
  {
    id: 'fn-5',
    slug: 'bundesliga-bayer-leverkusen-unbeaten-run',
    title: "Bayer Leverkusen extend Bundesliga's longest unbeaten run to 47 games",
    description:
      "Bayer Leverkusen broke yet another record as they extended the Bundesliga's all-time unbeaten run to 47 games with a dominant 3-0 victory over Werder Bremen. Granit Xhaka scored twice and set up the third as Xabi Alonso's side continue their march towards a second successive league title in scintillating fashion.",
    image: 'https://images.unsplash.com/photo-1461896836934-ffe607ba8211?w=800&q=80',
    category: 'Football',
    subCategory: 'Bundesliga',
    source: 'Kicker',
    author: 'Stefan Rommel',
    time: '5h ago',
    date: '2025-03-23T05:30:00Z',
    league: 'Bundesliga',
    venue: 'BayArena, Leverkusen',
    tags: ['Bayer Leverkusen', 'Bundesliga', 'Unbeaten', 'Record'],
  },
  {
    id: 'fn-6',
    slug: 'inter-milan-serie-a-leaders',
    title: 'Inter Milan reclaim Serie A top spot with comfortable win',
    description:
      "Inter Milan returned to the summit of Serie A with a 2-0 victory over Napoli at the Stadio Diego Armando Maradona. Lautaro Martínez scored his 22nd league goal of the season, while a clinical Marcus Thuram header sealed the points. The result puts Inter one point clear of AC Milan with eight games remaining.",
    image: 'https://images.unsplash.com/photo-1554143091-c41d76e5a2a9?w=800&q=80',
    category: 'Football',
    subCategory: 'Serie A',
    source: 'Gazzetta dello Sport',
    author: 'Fabio Licari',
    time: '6h ago',
    date: '2025-03-23T04:30:00Z',
    league: 'Serie A',
    venue: 'Stadio Maradona, Naples',
    tags: ['Inter Milan', 'Serie A', 'Lautaro Martinez', 'Napoli'],
  },
  {
    id: 'fn-7',
    slug: 'mls-inter-miami-white-house-visit',
    title: 'Inter Miami honoured at White House after historic MLS Cup victory',
    description:
      "Lionel Messi led Inter Miami's delegation to the White House as the club were officially recognised for their MLS Cup triumph. The President praised Messi's impact on growing football in America ahead of the 2026 World Cup. Fans gathered outside the White House for a glimpse of the Argentine legend during the ceremony.",
    image: 'https://images.unsplash.com/photo-1536183922588-166604504d5e?w=800&q=80',
    category: 'Football',
    subCategory: 'MLS',
    source: 'MLS Official',
    author: 'Steven Goff',
    time: '7h ago',
    date: '2025-03-23T03:30:00Z',
    league: 'MLS',
    venue: 'White House, Washington D.C.',
    tags: ['Inter Miami', 'Messi', 'MLS', 'White House'],
  },
  {
    id: 'fn-8',
    slug: 'fa-cup-wrexham-chelsea-preview',
    title: 'FA Cup Semi-Final: Can Wrexham topple Chelsea at Wembley?',
    description:
      "Wrexham's fairytale FA Cup run continues as Ryan Reynolds and Rob McElhenney's club face Premier League giants Chelsea in the semi-final at Wembley. The League One side have stunned three top-flight opponents already. Chelsea's unbeaten run in cup competitions this season makes them heavy favourites, but Wrexham's spirit has defied logic all tournament.",
    image: 'https://images.unsplash.com/photo-1540747913346-19e32dc3e97e?w=800&q=80',
    category: 'Football',
    subCategory: 'FA Cup',
    source: 'Sky Sports',
    author: 'Ben Grounds',
    time: '9h ago',
    date: '2025-03-23T01:30:00Z',
    league: 'FA Cup',
    venue: 'Wembley Stadium, London',
    tags: ['FA Cup', 'Wrexham', 'Chelsea', 'Semi-Final'],
  },
]