// src/shared/data/headlines.data.js

export const headlinesData = [
  {
    id: 'hl-1',
    slug: 'cowboys-likely-to-think-about-it',
    title: 'Source: Cowboys likely to think about it',
    description:
      'Multiple league insiders confirm that the Dallas Cowboys front office is actively evaluating their roster situation ahead of the upcoming trade deadline. The team is weighing several options as they look to bolster their chances for a playoff run this season.',
    image: 'https://images.unsplash.com/photo-1508098682722-e99c43a406b2?w=800&q=80',
    category: 'NFL',
    source: 'ESPN',
    author: 'Adam Schefter',
    time: '4m ago',
    date: '2025-03-23T10:15:00Z',
    tags: ['NFL', 'Cowboys', 'Trade'],
  },
  {
    id: 'hl-2',
    slug: 'cowboys-likely-to-let-him-go',
    title: 'Source: Cowboys likely to let him go',
    description:
      'The Cowboys are reportedly prepared to release the veteran player as part of a broader cap-management strategy. Club sources indicate the decision is imminent and could reshape the team\'s offensive lineup heading into the second half of the season.',
    image: 'https://images.unsplash.com/photo-1566577739112-5180d4bf9390?w=800&q=80',
    category: 'NFL',
    source: 'NFL Network',
    author: 'Ian Rapoport',
    time: '4m ago',
    date: '2025-03-23T10:12:00Z',
    tags: ['NFL', 'Cowboys', 'Release'],
  },
  {
    id: 'hl-3',
    slug: 'white-house-spokesman-told-about-this',
    title: 'White House spokesman told about this',
    description:
      'A White House press briefing touched on sports-related policy decisions, with the spokesperson confirming federal support for major sporting events scheduled to take place on American soil over the next two years, including the FIFA World Cup and Summer Olympics.',
    image: 'https://images.unsplash.com/photo-1540747913346-19e32dc3e97e?w=800&q=80',
    category: 'General',
    source: 'AP News',
    author: 'James Wilson',
    time: '6m ago',
    date: '2025-03-23T10:00:00Z',
    tags: ['Sports Policy', 'White House', 'FIFA'],
  },
  {
    id: 'hl-4',
    slug: 'panthers-leveraging-position',
    title: 'Panthers likely to think about leveraging',
    description:
      'The Carolina Panthers coaching staff is reportedly considering a strategic pivot in their offensive game plan. League analysts believe the team is looking to leverage their young quarterback talent more aggressively in upcoming fixtures.',
    image: 'https://images.unsplash.com/photo-1461896836934-ffe607ba8211?w=800&q=80',
    category: 'NFL',
    source: 'The Athletic',
    author: 'Mike Sando',
    time: '4m ago',
    date: '2025-03-23T09:58:00Z',
    tags: ['NFL', 'Panthers', 'Strategy'],
  },
  {
    id: 'hl-5',
    slug: 'panthers-trade-deadline-move',
    title: 'Panthers likely to think about leveraging',
    description:
      'Reports suggest the Panthers may make a bold move before the trade deadline, targeting a proven pass rusher to shore up their defensive line. The team has cap space available and scouting reports on several high-profile candidates.',
    image: 'https://images.unsplash.com/photo-1536183922588-166604504d5e?w=800&q=80',
    category: 'NFL',
    source: 'Pro Football Talk',
    author: 'Mike Florio',
    time: '4m ago',
    date: '2025-03-23T09:45:00Z',
    tags: ['NFL', 'Panthers', 'Trade Deadline'],
  },
  {
    id: 'hl-6',
    slug: 'panthers-offensive-strategy-2025',
    title: 'Panthers likely to think about leveraging',
    description:
      'Offensive coordinator details new play-calling philosophy aimed at maximizing efficiency in the red zone. The Panthers have struggled to convert scoring opportunities this season and believe a scheme overhaul could turn their campaign around.',
    image: 'https://images.unsplash.com/photo-1431324155629-1a6deb1dec8d?w=800&q=80',
    category: 'NFL',
    source: 'CBS Sports',
    author: 'Jason La Canfora',
    time: '4m ago',
    date: '2025-03-23T09:30:00Z',
    tags: ['NFL', 'Panthers', 'Offense'],
  },
  {
    id: 'hl-7',
    slug: 'krasner-rollercoasting-philly',
    title: 'Krasner: Rollercoasting on wheels for this in Philly',
    description:
      'Philadelphia\'s sports scene is buzzing as the city prepares for a big week of action across multiple leagues. Local authorities have confirmed enhanced security and transport measures to handle the influx of sports fans visiting the city.',
    image: 'https://images.unsplash.com/photo-1554143091-c41d76e5a2a9?w=800&q=80',
    category: 'General',
    source: 'Philadelphia Inquirer',
    author: 'Bob Ford',
    time: '4m ago',
    date: '2025-03-23T09:15:00Z',
    tags: ['Philadelphia', 'Sports', 'Events'],
  },
  {
    id: 'hl-8',
    slug: 'krasner-rollercoasting-miami',
    title: 'Krasner: Rollercoasting on wheels for this in Miami',
    description:
      'Miami is set to host a marquee sporting weekend with events spanning football, basketball, and tennis. City officials expect record tourism numbers as fans from across the country converge on South Florida for the packed sports calendar.',
    image: 'https://images.unsplash.com/photo-1486286701208-1d58e9338013?w=800&q=80',
    category: 'General',
    source: 'Miami Herald',
    author: 'Greg Cote',
    time: '4m ago',
    date: '2025-03-23T09:00:00Z',
    tags: ['Miami', 'Sports', 'Events'],
  },
  {
    id: 'hl-9',
    slug: 'miami-honoured-trump-white-house',
    title: 'Miami honoured by Trump at White House',
    description:
      'Inter Miami CF was welcomed to the White House in a ceremony recognising their historic MLS Cup victory. President Trump congratulated the club and its star players, calling the championship win a proud moment for American soccer on the global stage.',
    image: 'https://images.unsplash.com/photo-1431324155629-1a6deb1dec8d?w=800&q=80',
    category: 'Football',
    source: 'Reuters',
    author: 'Steve Kerrigan',
    time: '4m ago',
    date: '2025-03-23T08:45:00Z',
    tags: ['MLS', 'Inter Miami', 'White House'],
  },
]