// src/shared/data/otherSportsNews.data.js

export const otherSportsNewsData = [
  {
    id: 'os-1',
    slug: 'sinner-french-open-title-defence',
    title: 'Sinner begins French Open title defence with dominant straight-set win',
    description:
      "World No. 1 Jannik Sinner opened his French Open title defence in emphatic fashion, dismissing qualifier Alexei Popyrin 6-2, 6-1, 6-3 in just 87 minutes on Court Philippe-Chatrier. The Italian supreme in all departments, landing 85% of his first serves and unleashing 34 winners. Sinner is chasing an unprecedented calendar Grand Slam this season.",
    image: 'https://images.unsplash.com/photo-1461896836934-ffe607ba8211?w=800&q=80',
    category: 'Tennis',
    subCategory: 'Grand Slam',
    source: 'Tennis World',
    author: 'Christopher Clarey',
    time: '2h ago',
    date: '2025-03-23T08:00:00Z',
    event: 'French Open 2025',
    venue: 'Roland Garros, Paris',
    tags: ['Tennis', 'Sinner', 'French Open', 'Grand Slam'],
  },
  {
    id: 'os-2',
    slug: 'lakshya-sen-indonesia-masters-final',
    title: 'Lakshya Sen stuns world champion Shi Yuqi to reach Indonesia Masters final',
    description:
      "India's Lakshya Sen produced a stunning upset to reach his maiden BWF Super 1000 final, defeating reigning world champion Shi Yuqi of China 15-21, 21-18, 21-16 in a thrilling semi-final. The 24-year-old from Almora displayed exceptional court coverage and disguised drop shots to wear down the higher-ranked opponent.",
    image: 'https://images.unsplash.com/photo-1536183922588-166604504d5e?w=800&q=80',
    category: 'Badminton',
    subCategory: 'BWF Super 1000',
    source: 'BWF Official',
    author: 'Vinayakk M',
    time: '3h ago',
    date: '2025-03-23T07:00:00Z',
    event: 'Indonesia Masters 2025',
    venue: 'Istora Senayan, Jakarta',
    tags: ['Badminton', 'Lakshya Sen', 'India', 'BWF Super 1000'],
  },
  {
    id: 'os-3',
    slug: 'verstappen-saudi-arabia-gp-pole',
    title: 'Verstappen storms to pole position at Saudi Arabia Grand Prix',
    description:
      "Max Verstappen delivered a blistering lap to claim pole position for the Saudi Arabia Grand Prix in Jeddah, edging out Lando Norris by 0.123 seconds. The Dutchman's Red Bull looked in a class of its own through the high-speed sections of the Jeddah Corniche Circuit. Ferrari's Charles Leclerc and Carlos Sainz will start from third and fourth.",
    image: 'https://images.unsplash.com/photo-1554143091-c41d76e5a2a9?w=800&q=80',
    category: 'Formula 1',
    subCategory: 'Qualifying',
    source: 'Formula 1 Official',
    author: 'Lawrence Barretto',
    time: '4h ago',
    date: '2025-03-23T06:00:00Z',
    event: 'Saudi Arabia Grand Prix 2025',
    venue: 'Jeddah Corniche Circuit, Saudi Arabia',
    tags: ['Formula 1', 'Verstappen', 'Pole Position', 'Saudi Arabia GP'],
  },
  {
    id: 'os-4',
    slug: 'nba-lakers-celtics-rivalry-renewed',
    title: 'Lakers vs Celtics: Historic rivalry renewed in Finals rematch preview',
    description:
      "The Los Angeles Lakers and Boston Celtics are on a collision course for an NBA Finals rematch, with both clubs sitting atop their respective conferences. LeBron James shows no signs of slowing down at 40, averaging 28.4 points and 8.2 assists per game. The Celtics meanwhile boast the league's best defensive rating for the third straight season.",
    image: 'https://images.unsplash.com/photo-1486286701208-1d58e9338013?w=800&q=80',
    category: 'Basketball',
    subCategory: 'NBA',
    source: 'ESPN',
    author: 'Adrian Wojnarowski',
    time: '5h ago',
    date: '2025-03-23T05:00:00Z',
    event: 'NBA 2024-25 Season',
    venue: 'Various',
    tags: ['NBA', 'Lakers', 'Celtics', 'LeBron James'],
  },
  {
    id: 'os-5',
    slug: 'djokovic-australian-open-comeback',
    title: 'Djokovic mounts incredible comeback to reach Australian Open semis at 37',
    description:
      "Novak Djokovic defied age, a wrist injury, and a two-set deficit to reach the Australian Open semi-finals in a five-set epic lasting 4 hours 38 minutes. The 24-time Grand Slam champion saved five match points in the fourth set before running away with the decider 6-1. He will face Carlos Alcaraz in a tantalising semi-final showdown.",
    image: 'https://images.unsplash.com/photo-1508098682722-e99c43a406b2?w=800&q=80',
    category: 'Tennis',
    subCategory: 'Grand Slam',
    source: 'Tennis World',
    author: 'Simon Briggs',
    time: '6h ago',
    date: '2025-03-23T04:00:00Z',
    event: 'Australian Open 2025',
    venue: 'Melbourne Park, Melbourne',
    tags: ['Tennis', 'Djokovic', 'Australian Open', 'Grand Slam'],
  },
  {
    id: 'os-6',
    slug: 'axelsen-all-england-open-champion',
    title: "Axelsen crowned All England Open champion for record 5th time",
    description:
      "Viktor Axelsen of Denmark claimed his fifth All England Open title with a commanding performance against Kento Momota in the final, winning 21-18, 21-15 in 47 minutes. The world No. 1 displayed flawless technique throughout the tournament, dropping only one set on his way to the title. He dedicated the win to his young daughter.",
    image: 'https://images.unsplash.com/photo-1431324155629-1a6deb1dec8d?w=800&q=80',
    category: 'Badminton',
    subCategory: 'All England',
    source: 'Badminton World',
    author: 'Jack Sokol',
    time: '7h ago',
    date: '2025-03-23T03:00:00Z',
    event: 'All England Open 2025',
    venue: 'Utilita Arena Birmingham',
    tags: ['Badminton', 'Axelsen', 'All England', 'Denmark'],
  },
  {
    id: 'os-7',
    slug: 'hamilton-ferrari-debut-preview',
    title: "Lewis Hamilton's Ferrari debut: Can he win a record 8th world title?",
    description:
      "Lewis Hamilton's blockbuster move to Ferrari has sent seismic waves through Formula 1. The seven-time world champion is chasing an unprecedented eighth title in the iconic red car. We analyse the technical partnership, Ferrari's recent developments, and whether the SF-25 has what it takes to dethrone the dominant Red Bull.",
    image: 'https://images.unsplash.com/photo-1566577739112-5180d4bf9390?w=800&q=80',
    category: 'Formula 1',
    subCategory: 'Season Preview',
    source: 'Autosport',
    author: 'Scott Mitchell-Malm',
    time: '8h ago',
    date: '2025-03-23T02:00:00Z',
    event: 'Formula 1 2025 Season',
    venue: 'Various',
    tags: ['Formula 1', 'Hamilton', 'Ferrari', 'Championship'],
  },
  {
    id: 'os-8',
    slug: 'india-olympics-2028-preparation',
    title: "India's ambitious push for 10 medals at LA 2028 Olympics",
    description:
      "The Indian Olympic Association has unveiled a comprehensive roadmap targeting 10 medals at the 2028 Los Angeles Olympics, up from 6 at Paris 2024. Investment in athletics, boxing, wrestling, and shooting has been significantly increased. Star performers Neeraj Chopra, PV Sindhu, and Manu Bhaker are central to the multi-medal strategy.",
    image: 'https://images.unsplash.com/photo-1540747913346-19e32dc3e97e?w=800&q=80',
    category: 'Olympics',
    subCategory: 'Preparation',
    source: 'Times of India',
    author: 'Rohit Brijnath',
    time: '10h ago',
    date: '2025-03-23T00:00:00Z',
    event: 'LA Olympics 2028',
    venue: 'Los Angeles, USA',
    tags: ['Olympics', 'India', 'LA 2028', 'Neeraj Chopra'],
  },
]